### PR TITLE
fix: csv parser understand multi-measurements

### LINKED ISSUE #538: csv uploader: fails to parse csv with multiple measurements
If you use the CSV uploader to upload a CSV file with multiple measurement columns, it will fail. 

Attached is a CSV that recreates this issue. 

[multiple measurements.csv.zip](https://github.com/influxdata/ui/files/5852424/multiple.measurements.csv.zip)

Error from API: 
```
unable to parse 'baywheels_meta,host=ip-192-168-1-6.ec2.internal,station_id=412,lat=37.7328128005294,lon=-122.43414044380188,name=Glen\\ Park\\ BART\\ Station,region_id=3,short_name=SF-W19 external_id=external_id 1611262738549000000': invalid boolean
```

The CSV to LP converter should adhere to line protocol standards for multiple measurements as defined here: https://docs.influxdata.com/influxdb/cloud/reference/syntax/line-protocol/

### PR DESCRIPTION
**Pull request by genehynson**
Closes #538 

Allows CSV parser to handle multiple measurement columns when there are multiple types of the `_value` column involved. 

See https://github.com/influxdata/giraffe/blob/master/giraffe/src/utils/fromFlux.ts#L62

Screen Shot 2021-01-21 at 3 56 22 PM

- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

### CODE REVIEW

**Comment by hercules-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 51 | :red_circle:
accessibility | 65 | :yellow_circle:
best-practices | 87 | :green_circle:
seo | 80 | :yellow_circle:
pwa | null | :question:

**Comment by genehynson** [comment]
Giraffe issue to improve the UX of `fromFlux` in this scenario: https://github.com/influxdata/giraffe/issues/455

**Review by Asalem1 — COMMENTED** [review]
You’re absolutely crushing it. We should totally write some e2e tests on these to make sure all your hard work stays solid

File: src/buckets/components/context/csvUploaderProvider.tsx [hunk 1]
```diff
@@ -152,11 +153,20 @@ export const CsvUploaderProvider: FC<Props> = React.memo(({children}) => {
...
+            table.columnKeys
+              // Matches _value, _value ('number'), _value ('string'), etc. to find value
+              // https://github.com/influxdata/giraffe/blob/master/giraffe/src/utils/fromFlux.ts#L62
+              .filter(c => /_value( \('\w*'\))?/g.test(c))
+              .forEach(c => {
+                if (table.getColumn(c)?.[i]) {
+                  value = table.getColumn(c)[i]
+                  valueColumn = c
+                }
+              })
```
Comment (Asalem1) [inline src/buckets/components/context/csvUploaderProvider.tsx:165]: I think we might be able to simplify this by simply passing in the datatype as the second parameter in the `table.getColumn` function:

https://github.com/influxdata/giraffe/blob/master/giraffe/src/utils/newTable.ts#L25

**Review by Asalem1 — APPROVED** [review]

File: src/buckets/components/context/csvUploaderProvider.tsx (hunk 1 above)
Comment (Asalem1) [reply src/buckets/components/context/csvUploaderProvider.tsx:165]: Turns out I was running and giraffe is 💩  with this.  Looks good to me!

**Review by Asalem1 — APPROVED** [review]
