### PR TITLE
fix: update Giraffe to update formatStatValue

### LINKED ISSUE #3519: InfluxDB Cloud: number format
The number format in the UI is broken in my instance of InfluxDB Cloud. A "Single Stat"cell for instance shows the following value:

111.474.245.00

The thousands separator is german style. Fine with me. But the decimal separator should be a "," instead of the ".".
Am I missing something?

Best,
Keith

### PR DESCRIPTION
**Pull request by TCL735**
Closes #3519 

- updates Giraffe to update `formatStatValue`
- copies `formatStatValue` from Giraffe for posterity
     _note_: `formatStatValue` should not be implemented by UI and will be removed in a separate pull request.

### CODE REVIEW

File: src/visualization/utils/formatStatValue.ts [hunk 1]
```diff
@@ -35,19 +35,14 @@ export const formatStatValue = (
...
+  const formatter = Intl.NumberFormat(undefined, {
+    minimumFractionDigits: digits,
+    maximumFractionDigits: digits,
+  })
+
+  if (isNumber(value)) {
+    localeFormattedValue = formatter.format(Number(value))
+  } else if (isString(value)) {
     localeFormattedValue = value
   } else {
```
Comment (TCL735) [inline src/visualization/utils/formatStatValue.ts:47]: This is not needed to fix the issue, however, we are adding this change for posterity. We want this change in the history before the whole file is removed (in a separate pull request).

Comment (TCL735) [reply src/visualization/utils/formatStatValue.ts]: Also, there is a minor difference. Giraffe uses utils `isNumber` and `isString` while here in the UI we simply use `typeof` to check the type.

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 55 | :red_circle:
accessibility | 97 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=3578)

**Comment by asalem1** [comment]
Is there an issue to not have this in the UI do that we don’t lose connect later on?

File: src/visualization/utils/formatStatValue.ts (hunk 1 above)
Comment (hoorayimhelping) [reply src/visualization/utils/formatStatValue.ts]: >We want this change in the history before the whole file is removed (in a separate pull request).

why do we want that?

**Review by hoorayimhelping — APPROVED** [review]
code looks fine, just had a question about the process involved

**Comment by TCL735** [comment]
> Is there an issue to not have this in the UI do that we don’t lose connect later on?

`formatStatValue` supports only SingleStat and Gauge. So, it should have been removed when those two visualizations' implementations got removed from the UI. (They live in Giraffe.)

We can reference that issue to complete the removal of `formatStatValue`
