### PR TITLE
fix: zoom out fixes

### LINKED ISSUE #1758: UI:  differentiate double from single clicks
counterpart of giraffe#617

now that we add point annotations with a shift+click; need to update the ui and update the tests.

### PR DESCRIPTION
**Pull request by jrenee42**
Closes #1758

now that we add point annotations with a shift+click; need to update the ui and update the tests.

### CODE REVIEW

File: src/annotations/components/controlBar/AnnotationsControlBar.tsx [hunk 1]
```diff
@@ -2,21 +2,15 @@
...
+import {ComponentSize, InfluxColors, TextBlock} from '@influxdata/clockface'
 
 import {useSelector} from 'react-redux'
 import {isAnnotationsModeEnabled} from 'src/annotations/selectors'
+import Toolbar from 'src/shared/components/toolbar/Toolbar'
 
 export const AnnotationsControlBar: FC = () => {
   const infoText1 =
-    'Click on a graph to create a point annotation, click + shift + drag to create a range annotation.'
+    'Shift + click on a graph to create a point annotation, click + shift + drag to create a range annotation.'
```
Comment (hoorayimhelping) [inline src/annotations/components/controlBar/AnnotationsControlBar.tsx:13]: should the `click + shift + drag to create a range annotation.` text be flagged behind `rangeAnnotations`?

Comment (jrenee42) [reply src/annotations/components/controlBar/AnnotationsControlBar.tsx:13]: it will be; in the next PR that I do.

Comment (jrenee42) [reply src/annotations/components/controlBar/AnnotationsControlBar.tsx:13]: see: https://github.com/influxdata/ui/pull/1761

**Review by hoorayimhelping — APPROVED** [review]
