### PR TITLE
fix: remove react warning

### LINKED ISSUE #1853: React Memory Leak: SubmitQueryButton
### Background
Fix the memory leak in `SubmitQueryButton`

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in SubmitQueryButton (created by ConnectFunction)
    in ConnectFunction (created by TimeMachineQueries)
    in div (created by FlexBox)
    in FlexBox (created by FlexBox)
    in FlexBox (created by TimeMachineQueries)
    in div (created by TimeMachineQueries)
    in div (created by TimeMachineQueries)
```

### Steps to reproduce
1. Create a cell in a dashboard
1. Edit the cell
1. Click `Submit` then immediately click the Green Check mark that saves the cell. Click this while the query is running.
1. The warning should fire in the console

### PR DESCRIPTION
**Pull request by subirjolly**
Closes #1853

### CODE REVIEW

**Review by hoorayimhelping — APPROVED** [review]

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 57 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=master)

File: src/timeMachine/components/SubmitQueryButton.tsx [hunk 1]
```diff
@@ -77,6 +77,10 @@ class SubmitQueryButton extends PureComponent<Props> {
   }
 
   componentWillUnmount() {
+    // Clearing and removing timer before the component is unmounted
+    clearTimeout(this.timer)
+    delete this.timer
```
Comment (Asalem1) [inline src/timeMachine/components/SubmitQueryButton.tsx:82]: why do we want to delete the timer before the component unmounts?

**Review by genehynson — APPROVED** [review]

File: src/timeMachine/components/SubmitQueryButton.tsx (hunk 1 above)
Comment (subirjolly) [reply src/timeMachine/components/SubmitQueryButton.tsx:82]: because `setTimeout` tries to delete it after the component has been unmounted. So, deleting the timer here stops setTimeout from happening.

Comment (subirjolly) [reply src/timeMachine/components/SubmitQueryButton.tsx:82]: right here: https://github.com/influxdata/ui/pull/1922/files/588effe69d43f55b975af95a4d4a109328e43ff6#diff-6504aaf0fbb0dc6a4a0968ece1d85325956fa677fde7ce63d5ebb35ee0c36360R62

**Review by Asalem1 — APPROVED** [review]
