### PR TITLE
test: more fix on flaky test for schema browser

### LINKED ISSUE #4907: Flaky test in Flux Query Builder
The cypress test for Flux Query Builder (`fluxQueryBuilder.test.ts`) is flaky. The tests passes on local machines, but fail on CI. 

It may related to local storage and/or cypress parallelization.

Here is one of the failed monitor CI tests:
https://app.circleci.com/pipelines/github/influxdata/monitor-ci/12801

### PR DESCRIPTION
**Pull request by appletreeisyellow**
Closes #4907 

This PR fixed the flaky test in schema browser by 1) using cypress `within()` to limit the scope of search for DOM, 2) adding dependent function in `useMemo` 

### Checklist

Authors and Reviewer(s), please verify the following:

- [x] A PR description, regardless of the triviality of this change, that communicates the value of this PR
- [x] [Well-formatted conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/) that provide context into the change
- [x] Documentation updated or issue created (provide link to issue/PR)
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] Feature flagged, if applicable

### CODE REVIEW

File: src/dataExplorer/components/FieldSelector.tsx [hunk 1]
```diff
@@ -84,10 +91,10 @@ const FieldSelector: FC = () => {
     ))
   }
 
-  const handleLoadMore = () => {
+  const handleLoadMore = useCallback(() => {
     const newIndex = fieldsToShow.length + LOAD_MORE_LIMIT
     setFieldsToShow(fields.slice(0, newIndex))
-  }
+  }, [fieldsToShow])
```
Comment (drdelambre) [inline src/dataExplorer/components/FieldSelector.tsx:97]: you gotta add `fields` and `setFieldsToShow` here as well!

Comment (appletreeisyellow) [reply src/dataExplorer/components/FieldSelector.tsx:97]: oh! let me try!

**Review by drdelambre — APPROVED** [review]
