### PR TITLE
feat: fixed some bugs and allowed users to query from the pipe icon

### LINKED ISSUE #417: Notebooks:  I can preview/run a notebook
## User Problem
As a notebooks early access user, I don't know how to preview/run the notebook and try clicking the prompt below the cell that says "Click Preview to See Results"

Example from @abalone23, "I tried clicking it multiple times before reading the text that said to click Preview located at the top of the notebook."

## Proposed solution
Given: I have a notebook with at least one cell
When: I click the Play button or the text "Click Preview/Run to See Results"
Then: The notebook is Previewed/Ran

### PR DESCRIPTION
**Pull request by Asalem1**
Closes #417

The primary purpose of this PR is to allow users to run queries when clicking the `play` icon in the pipe:

run-query

This PR also addresses some random issues that were causing Notebooks to be wonky, namely:

- The run button never being disabled due to a miscalculation in identifying metric selector queries
- removing aggregateOfAggregates as a hack to run queries explicitly when updating an aggregate type and just running the query when an aggregate type is changed
- Only changes the loading state of pipes that are being run

### CODE REVIEW

File: src/flows/components/header/Submit.tsx [hunk 1]
```diff
@@ -16,130 +9,51 @@ import {
...
+  const _range = useMemo(
+    () => `${flow.range.lower} to ${flow.range.upper || 'now'}`,
+    [flow.range]
+  )
 
   const hasQueries = useMemo(() => {
     return !!flow.data.all
+      .filter(p => {
+        // this condition ensures that empty metric selectors are filtered out
+        if (p?.type === 'metricSelector') {
```
Comment (drdelambre) [inline src/flows/components/header/Submit.tsx:42]: the submit button shouldn't know about the implementation details of a self registering type. can we use generateMap somehow instead? like "if stages.length" or something

File: src/flows/components/header/Submit.tsx [hunk 2]
```diff
@@ -151,9 +65,9 @@ export const Submit: FC = () => {
           text={runMode}
           className="flows--submit-button"
           icon={IconFont.Play}
-          submitButtonDisabled={!hasQueries}
+          submitButtonDisabled={hasQueries === false}
```
Comment (drdelambre) [inline src/flows/components/header/Submit.tsx:68]: this change isn't needed right? just the filter above to make the button disabled?

File: src/flows/context/query.tsx [hunk 3]
```diff
@@ -81,11 +96,14 @@ const findOrgID = (text, buckets) => {
...
 export const QueryProvider: FC = ({children}) => {
   const {flow} = useContext(FlowContext)
+  const {runMode} = useContext(RunModeContext)
+  const {add, update} = useContext(ResultsContext)
   const variables = useSelector((state: AppState) => getVariables(state))
   const buckets = useSelector((state: AppState) => getSortedBuckets(state))
   const bucketsLoadingState = useSelector((state: AppState) =>
     getStatus(state, ResourceType.Buckets)
   )
+  const [isLoading, setLoading] = useState(RemoteDataState.NotStarted)
```
Comment (drdelambre) [inline src/flows/context/query.tsx:106]: this isn't it's own state, but a derived state. it's not that `queryAll` sets the state and keeps track of it, but that it's a conglomeration of all of the stages loading state. instead of a useState, it's more of a `flows.meta.all.reduce(meta => if any are loading, show the loading state), RemoteDataState.NotStarted)'

File: src/flows/context/query.tsx [hunk 4]
```diff
@@ -191,12 +209,72 @@ export const QueryProvider: FC = ({children}) => {
...
+      return
+    }
+
+    const map = generateMap(runMode === RunMode.Run)
+
+    if (!map.length) {
+      return
+    }
+
+    event('Flow Submit Button Clicked')
```
Comment (drdelambre) [inline src/flows/context/query.tsx:231]: this event should exist on the submit button only, and not on the underlying implementation of the submit logic. then if we wanna change how we submit something, the events in GA keep ticking

File: src/flows/context/query.tsx (hunk 3 above)
Comment (drdelambre) [reply src/flows/context/query.tsx:106]: and yes i know that's not how it worked before. but i think we're in a better place now with this

File: src/flows/pipes/MetricSelector/AggregateWindowSelector.tsx [hunk 5]
```diff
@@ -31,8 +34,9 @@ const AggregateFunctionSelector: FC = () => {
         function: aggregateFunction.name,
       })
       update({aggregateFunction})
+      queryAll()
```
Comment (drdelambre) [inline src/flows/pipes/MetricSelector/AggregateWindowSelector.tsx:37]: omg so much better

File: src/flows/shared/ResizerHeader.tsx [hunk 6]
```diff
@@ -34,16 +40,22 @@ const ResizerHeader: FC<Props> = ({
...
   const {readOnly} = useContext(PipeContext)
+  const {queryAll} = useContext(QueryContext)
   const glyph = visibility === 'visible' ? IconFont.EyeOpen : IconFont.EyeClosed
   const className = classnames('panel-resizer--header', {
     'panel-resizer--header__multiple-controls':
       toggleVisibilityEnabled || additionalControls,
     [`panel-resizer--header__${visibility}`]: resizingEnabled && visibility,
   })
 
+  const handleSubmit = () => {
```
Comment (drdelambre) [inline src/flows/shared/ResizerHeader.tsx:51]: :exploding_head:

File: src/flows/components/header/Submit.tsx (hunk 2 above)
Comment (Asalem1) [reply src/flows/components/header/Submit.tsx:68]: It isn't necessary, but i think it makes it a bit more understandable

File: src/flows/components/header/Submit.tsx (hunk 1 above)
Comment (Asalem1) [reply src/flows/components/header/Submit.tsx:42]: I hear ya, I'll give the stages one a shot

File: src/flows/context/query.tsx (hunk 3 above)
Comment (Asalem1) [reply src/flows/context/query.tsx:106]: Gotcha. SO then this should be obtainable in the submit context

File: src/flows/context/query.tsx (hunk 4 above)
Comment (Asalem1) [reply src/flows/context/query.tsx:231]: Totally

File: src/flows/components/header/Submit.tsx [hunk 7]
```diff
@@ -16,130 +9,64 @@ import {
...
-    if (isLoading === RemoteDataState.Loading) {
-      return
-    }
-
-    const map = generateMap(runMode === RunMode.Run)
-
-    if (!map.length) {
-      return
+  const status = flow.meta.all.reduce((_, curr) => {
+    switch (curr?.loading) {
```
Comment (drdelambre) [inline src/flows/components/header/Submit.tsx:57]: we gotta get a little more complicated with this one. as is, this'll only return the loading state of the last pipe. instead, lets change it back to an `isLoading` boolean, but write the reduce like this:
```
const isLoading = flow.meta.all.reduce((acc, curr) => {
  return acc || curr.loading === RemoteDataState.Loading
}, false)
```
with this, as long as any of them are still loading, no mater how they were triggered or how long they take, the submit button stays loading

File: src/flows/context/query.tsx [hunk 8]
```diff
@@ -191,12 +206,83 @@ export const QueryProvider: FC = ({children}) => {
...
 
+  const forceUpdate = (id, data) => {
+    try {
+      update(id, data)
+    } catch (_e) {
+      add(id, data)
+    }
+  }
+
+  const status = flow.meta.all.reduce((_, curr) => {
```
Comment (drdelambre) [inline src/flows/context/query.tsx:217]: see the note above for how to change this up

**Review by drdelambre — APPROVED** [review]
:fire:

File: src/flows/components/header/Submit.tsx [hunk 9]
```diff
@@ -16,130 +9,51 @@ import {
...
 
   const hasQueries = useMemo(() => {
     return !!flow.data.all
+      .filter(p => {
+        // this condition ensures that empty metric selectors are filtered out
+        if (p?.type === 'metricSelector') {
+          return !!p?.bucket
+        }
+        return true
+      })
```
Comment (genehynson) [inline src/flows/components/header/Submit.tsx]: nit: could be a ternary if you want. `return p?.type === 'metricSelector' ? !!p?.bucket : true`

**Review by genehynson — APPROVED** [review]
one nit, but lgtm!
