### PR TITLE
fix: templates page font sizes

### LINKED ISSUE #3023: Templates Page font size standardization
Needs to rationalize some of the font size choices here as things don't look right

### PR DESCRIPTION
**Pull request by ChitlangeSahas**
Closes #3023

Minor UI fixes.

Before:

Capture d’écran, le 2021-11-08 à 4 22 35 PM

After: 

Capture d’écran, le 2021-11-08 à 4 03 46 PM

### CODE REVIEW

**Review by TCL735 — APPROVED** [review]

File: src/templates/components/CommunityTemplateHumanReadableResource.tsx [hunk 1]
```diff
@@ -11,17 +11,18 @@ import {event} from 'src/cloud/utils/reporting'
...
-  ResourceType,
   Check,
+  Dashboard,
+  Label,
   NotificationEndpoint,
   NotificationRule,
+  ResourceType,
+  Task,
+  Telegraf,
+  Variable,
```
Comment (ChitlangeSahas) [inline src/templates/components/CommunityTemplateHumanReadableResource.tsx:23]: Alphabetically arranged.

File: src/templates/containers/CommunityTemplates.scss [hunk 2]
```diff
@@ -99,6 +99,7 @@
 }
 
 .community-templates--resources-table {
+  margin-left: 1.4em;
```
Comment (ChitlangeSahas) [inline src/templates/containers/CommunityTemplates.scss:102]: This is so that the resource table aligns with the header text instead of the caret end.

**Review by hoorayimhelping — APPROVED** [review]

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 61 | :yellow_circle:
accessibility | 97 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 93 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=3182)
