### PR TITLE
fix: centralize the getter for the query needed by adaptive zoom

### LINKED ISSUE #5319: Query Zoom (GA) - Bug: Notebooks & New Data Explorer: zooming in does not issue a query properly for more data
- [ ] In Notebooks, zooming does not actually issue a proper query, but it is supposed to. The probable cause is that the query is buried somewhere in context rather than redux state.

- [ ] In the New Data Explorer, zooming also does not issue a proper query.

### PR DESCRIPTION
**Pull request by TCL735**
Closes #5319  

- allows adaptive zoom to be used in Notebooks by getting the right context to access the query
- allows adaptive zoom to be used in New Data Explorer by getting the right context to access the query

Here are the 3 different primary ways to visualize a graph and the adaptive zoom working in all of them:

https://user-images.githubusercontent.com/10736577/185716360-d560f815-2ed9-4424-95a5-ed37081135f9.mp4

### CODE REVIEW

File: src/visualization/types/Graph/view.tsx [hunk 1]
```diff
@@ -181,13 +182,14 @@ const XYPlot: FC<Props> = ({
     return useVisYDomainSettings(storedDomain, memoizedYColumnData)
   }
 
+  const zoomQuery = useZoomQuery(properties)
```
Comment (hoorayimhelping) [inline src/visualization/types/Graph/view.tsx:185]: should this call be moved down so that it's inside the 

```ts
if (isFlagEnabled('zoomRequery') {
```
check?

**Review by hoorayimhelping — APPROVED** [review]

File: src/visualization/types/Graph/view.tsx (hunk 1 above)
Comment (TCL735) [reply src/visualization/types/Graph/view.tsx:185]: no, it's a hook and cannot be called conditionally.
