### PR TITLE
fix: generate correct name for orgs tokens

### LINKED ISSUE #3174: Tokens: generateDescription function in utils creates incorrect name for Orgs read/write token
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Go to tokens page 
2. click on `Generate API Token` button
3. create a read/write token for `All Orgs` without adding description 

**Expected behavior:**
A token with `Read orgs Write orgs` description should be created 

**Actual behavior:**
A token with `Read orgs dev Write orgs dev` description is created 

**Visual Proof:**
 

## About your environment

**Environment info:**

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

### PR DESCRIPTION
**Pull request by blegesse-git**
Closes #3174 

Added an if statement inside `generateDescription` function in utils that checks if received api permission array is an orgs permission. If true, the function will take org's unique data structure into account and generate its name accordingly.

Top token has correct description (fix) . Botton token is wrong (before fix) 
Screen Shot 2021-11-08 at 12 55 53 PM

### CODE REVIEW

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 60 | :red_circle:
accessibility | 97 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 93 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=3175)

File: src/authorizations/utils/permissions.ts [hunk 1]
```diff
@@ -329,14 +329,20 @@ export const generateDescription = apiPermissions => {
...
+        }  `
       } else {
-        generatedDescription += `${capitalize(perm.action)} ${
-          perm.resource.type
-        } `
+        if (perm.resource.name) {
+          generatedDescription += `${capitalize(perm.action)} ${
+            perm.resource.type
+          } ${perm.resource.name} `
+        } else {
```
Comment (hoorayimhelping) [inline src/authorizations/utils/permissions.ts:341]: it might be easier to read without all the extra brackets and syntax if instead of an `else` this is just set as a default case. I personally find it easier to follow, as it generally puts the default case at the top, then follows it with a special case triggered by a conditional

```ts
} else {
  generatedDescription += `${capitalize(perm.action)} ${perm.resource.type} `
  if (perm.resource.name) {
    generatedDescription += `${capitalize(perm.action)} ${
      perm.resource.type
    } ${perm.resource.name} `
  }
}
```

**Review by hoorayimhelping — APPROVED** [review]

File: src/authorizations/utils/permissions.ts [hunk 2]
```diff
@@ -329,14 +329,20 @@ export const generateDescription = apiPermissions => {
...
+          generatedDescription += `${capitalize(perm.action)} ${
+            perm.resource.type
+          } `
```
Comment (hoorayimhelping) [inline src/authorizations/utils/permissions.ts:344]: I originally left a comment on the this about structure, but after looking over it more clearly (like I should have done _before_ leaving the comment), I realized the comment was wrong because it didn't take into account the concatenation operator. My bad!
