### PR TITLE
fix: monaco syntax highlighting, other expression bugs

### LINKED ISSUE #2636: Monaco syntax highlighting is broken
Syntax highlighting is broken in production for both data explorer and notebooks.

image

### PR DESCRIPTION
**Pull request by genehynson**
Closes #2636 

- fixes monaco syntax highlighting by moving the monaco editor out of the Notification panel's view and into its own component. 
- adds `${ }` around the inserted variables
- handles queries without measurements, fields, tags

image

image

### CODE REVIEW

**Review by drdelambre — APPROVED** [review]

File: src/flows/pipes/Notification/NotificationMonacoEditor.tsx [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+  onChangeText,
+  setEditorInstance,
+}) => {
+  const editorDidMount = (editor: EditorType) => {
+    if (setEditorInstance) {
+      setEditorInstance(editor)
+    }
+  }
+
+  const onChange = (text: string) => {
```
Comment (subirjolly) [inline src/flows/pipes/Notification/NotificationMonacoEditor.tsx:34]: you don't need this. you can just pass `onChangeText` directly

File: src/flows/pipes/Notification/view.tsx [hunk 2]
```diff
@@ -172,7 +174,7 @@ const Notification: FC<PipeProp> = ({Context}) => {
             p.lineNumber,
             p.column
           ),
-          text: ` r.${exp} `,
+          text: ` \$\{r.${exp}\} `,
```
Comment (subirjolly) [inline src/flows/pipes/Notification/view.tsx:177]: just wondering, why this change?

Comment (genehynson) [reply src/flows/pipes/Notification/view.tsx:177]: I originally forgot that the variables are supposed to be put into the alert message like this: `${r.column}` instead of `r.column`

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 57 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=2640)

**Review by subirjolly — APPROVED** [review]
