### PR TITLE
fix(6598): properly use default static legend height

### LINKED ISSUE #6598: SQL editor issues with 'Display Static Legend'
In the SQL editor, I noticed a couple of things regarding the 'Display Static Legend':
1. if the editor is about 50% the window height or so, when you click 'Show' to display the static legend, it is not viewable until I make the editor vertically smaller. This might be because of '2', below
2. The 'Height' field under Display Static Legend seems to default to 5%. Even with the editor closed, that isn't a usable height (see no entries, just the header). Maybe 15% is a better default?
3. when sliding the Height, the displayed graph gets resized, but the contents get messed up until I run 'Run' again

I'm told that these issues are in the legacy/shared code. I wonder if setting the default height to 15% would be enough to close 1 and 2 with minimal effort? 3 can be worked around by clicking 'Run' again (though one has to know to do that).

### PR DESCRIPTION
**Pull request by wiedld**
Closes #6598 

Was not properly consuming the default versus the not_set. The default should be 20%.

## Vid

https://user-images.githubusercontent.com/10232835/218907789-b6ace46b-230a-47b3-819c-fd0b777b6407.mov

## Checklist
- [x] A PR description, regardless of the triviality of this change, that communicates the value of this PR
- [x] [Well-formatted conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/) that provide context into the change
- [x] Documentation updated or issue created (provide link to issue/PR)
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] Feature flagged, if applicable

### CODE REVIEW

File: src/visualization/components/internal/StaticLegend.tsx [hunk 1]
```diff
@@ -91,14 +92,15 @@ const StaticLegend: FC<Props> = ({properties, update}) => {
...
 
-  React.useEffect(() => {
-    if (
-      heightRatio === STATIC_LEGEND_HEIGHT_RATIO_NOT_SET &&
-      heightRatio !== defaultHeightRatio
-    ) {
-      setHeightRatio(defaultHeightRatio)
+  useEffect(() => {
+    setHeightRatio(defaultHeightRatio)
+  }, [defaultHeightRatio])
```
Comment (wiedld) [inline src/visualization/components/internal/StaticLegend.tsx:97]: if new default from parent --> then set.

File: src/visualization/components/internal/StaticLegend.tsx [hunk 2]
```diff
@@ -91,14 +92,15 @@ const StaticLegend: FC<Props> = ({properties, update}) => {
...
+
+  useEffect(() => {
+    if (showOptions && heightRatio === STATIC_LEGEND_HEIGHT_RATIO_NOT_SET) {
+      updateHeightRatio(STATIC_LEGEND_HEIGHT_RATIO_DEFAULT)
     }
-  }, [defaultHeightRatio, heightRatio])
+  }, [showOptions])
```
Comment (wiedld) [inline src/visualization/components/internal/StaticLegend.tsx:103]: If open the "show" on the legend, and it has the NOT_SET being used --> then override with the default hieght.

File: src/visualization/components/internal/StaticLegend.tsx [hunk 3]
```diff
@@ -81,7 +82,7 @@ const StaticLegend: FC<Props> = ({properties, update}) => {
   const {valueAxis} = staticLegend
   const {
     colorizeRows = false, // undefined is considered false because of omitempty
-    heightRatio: defaultHeightRatio = STATIC_LEGEND_HEIGHT_RATIO_NOT_SET,
+    heightRatio: defaultHeightRatio = STATIC_LEGEND_HEIGHT_RATIO_DEFAULT,
```
Comment (wiedld) [inline src/visualization/components/internal/StaticLegend.tsx:85]: This does not make a difference for most of the charts, since it had a default of NOT_SET (a.k.a. 0 height) hardcoded.

**Review by eatondustin1 — APPROVED** [review]
LGTM!

**Review by wdoconnell — APPROVED** [review]
