### PR TITLE
fix: updates default values and sets explict values where appropriate for Hover and Static Legends

### LINKED ISSUE #1855: Static Legend: view options have inconsistent default values
Some existing cells in Tools seem to have inconsistent default view options when cell editing is opened. Some of the inconsistencies observed include:

- Hover Legend does not have any orientation selected
- Hover Legend's opacity slider is affect Static Legend's opacity even while Static Legend's own opacity is stationary
- Static Legend's colorize rows toggle is sometimes on and sometimes off (the rendering matches) by default

### PR DESCRIPTION
**Pull request by TCL735**
Closes #1855 

orientation:
- added checks for 0 and -1 for vertical into the orientation toggle component
- updates will explicitly use -1 for vertical

opacity:
- added checks for valid opacity into the opacity slider component
- static legend will explicitly set a default opacity

### CODE REVIEW

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 45 | :red_circle:
accessibility | 72 | :yellow_circle:
seo | 67 | :yellow_circle:
pwa | null | :hankey:
best-practices | 75 | :yellow_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=master)

**Comment by genehynson** [comment]
> Metric	Score	Level
> performance	45	🔴
> accessibility	72	🟡
> seo	67	🟡
> pwa	null	💩
> best-practices	75	🟡
> [Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=master)

Oof what happen to these scores?? Can you rerun the `cloud-lighthouse` job and see if it was just a flake or if these scores are realistic for this PR?

**Review by zoesteinkamp — APPROVED** [review]
static legend fix looks promising

File: src/visualization/components/internal/HoverLegend.tsx [hunk 1]
```diff
@@ -179,8 +181,18 @@ const HoverLegend: FC<HoverLegendProps> = ({properties, update}) => {
   }
 
   const handleSetOrientation = (threshold: number): void => {
+    let validThreshold = threshold
```
Comment (hoorayimhelping) [inline src/visualization/components/internal/HoverLegend.tsx:184]: is this assignment necessary since it's an `if/else` ?

i think it should probably look closer to:

```ts
    let validThreshold
    if (
      typeof threshold !== 'number' ||
      threshold !== threshold ||
      threshold > 0
    ) {
      validThreshold = LEGEND_ORIENTATION_THRESHOLD_HORIZONTAL
    } else {
      validThreshold = LEGEND_ORIENTATION_THRESHOLD_VERTICAL
    }

File: src/visualization/components/internal/LegendOptions.tsx [hunk 2]
```diff
@@ -137,9 +138,17 @@ export const OpacitySlider: FC<OpacitySliderProps> = ({
...
 }) => {
-  // without the toFixed(0) sometimes you
-  // can get numbers like 45.000009% which we want to avoid
-  const percentLegendOpacity = (legendOpacity * 100).toFixed(0)
+  let validOpacity = legendOpacity
+  if (
+    typeof validOpacity !== 'number' ||
+    validOpacity !== validOpacity ||
+    validOpacity < LEGEND_OPACITY_MINIMUM ||
+    validOpacity > LEGEND_OPACITY_MAXIMUM
```
Comment (hoorayimhelping) [inline src/visualization/components/internal/LegendOptions.tsx:146]: what do you think about inverting this? i think inverting the meaning will show it being a default a little better.

```ts
let validOpacity = LEGEND_OPACITY_DEFAULT
  if (
    typeof legendOpacity === 'number' &&
    legendOpacity === legendOpacity &&
    legendOpacity > LEGEND_OPACITY_MINIMUM &&
    legendOpacity < LEGEND_OPACITY_MAXIMUM
  ) {
    validOpacity = legendOpacity
  }

File: src/visualization/components/internal/StaticLegend.tsx [hunk 3]
```diff
@@ -138,8 +140,18 @@ const StaticLegend: FC<Props> = ({properties, update}) => {
   }
 
   const handleSetOrientation = (threshold: number): void => {
+    let validThreshold = threshold
```
Comment (hoorayimhelping) [inline src/visualization/components/internal/StaticLegend.tsx:143]: same question here with this needing to be set since it's an `if/else`

**Review by hoorayimhelping — APPROVED** [review]
looks good to me, just some stylistic suggestions to make the intent of the code a little bit more clear

File: src/visualization/components/internal/HoverLegend.tsx (hunk 1 above)
Comment (TCL735) [reply src/visualization/components/internal/HoverLegend.tsx:184]: Yeah this reads better.

File: src/visualization/components/internal/LegendOptions.tsx (hunk 2 above)
Comment (TCL735) [reply src/visualization/components/internal/LegendOptions.tsx:146]: Sure thing. This reads better.
