### PR TITLE
fix: separate property name from input label description

### LINKED ISSUE #676: Axis Ticks Generator not working
The new feature behind the feature flag `axisTicksGenerator` is not working even when turned on. This affects all graph types. ~~Most likely this is due to the recent changes to the rendering pipeline.~~

### PR DESCRIPTION
**Pull request by TCL735**
Closes #676 

As a follow-up to https://github.com/influxdata/ui/pull/654 we should also change the property names so that they don't get affected by trivial labeling changes. My bad. Never link something important like an interface property with something trivial or fungible.

- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [ ] Tests pass

### CODE REVIEW

**Comment by hercules-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 42 | :red_circle:
accessibility | 65 | :yellow_circle:
best-practices | 87 | :green_circle:
seo | 80 | :yellow_circle:
pwa | null | :question:

File: src/visualization/components/internal/AxisTicksGenerator.tsx [hunk 1]
```diff
@@ -111,20 +110,22 @@ const AxisTicksGenerator: FC<Props> = ({
...
             initialTickOptionValue={totalTicks}
             label="Total Tick Marks"
             update={update}
           />
           <TimeTickInput
             axisName={axisName}
+            tickPropertyName="tickStart"
             tickOptions={generateAxisTicks}
             initialTickOptionValue={tickStart}
-            label="Start Tick Marks At"
```
Comment (drdelambre) [inline src/visualization/components/internal/AxisTicksGenerator.tsx:123]: how come this is removed?

Comment (TCL735) [reply src/visualization/components/internal/AxisTicksGenerator.tsx:123]: This prop wasn't being used. All of the `labels` in the child component have literal strings.

**Review by joelfried — APPROVED** [review]

**Review by drdelambre — APPROVED** [review]
