### PR TITLE
fix: update Gauge arc length to 1.5 PI when using Giraffe

### LINKED ISSUE #2021: Gauge: new gauge should look similar to old gauge
The new gauge from Giraffe is using the default arc length of π. Previously, the old gauge had an arc length that is longer than π and is somewhere between 1.5π - 2π

New gauge should not look so drastically different than old gauge. Please restore the arc length of gauge to be similar.

Here is a video showing their difference:

https://user-images.githubusercontent.com/10736577/125719128-651701be-c94d-4539-975d-d0487c631546.mp4

### PR DESCRIPTION
**Pull request by TCL735**
Closes #2021 

Updates gauge arc length to 1.5π and moves the gauge value slightly lower to accommodate long prefix/suffix combinations

Screen Shot 2021-07-14 at 8 05 46 PM

### CODE REVIEW

**Review by hoorayimhelping — APPROVED** [review]

File: src/visualization/types/Gauge/constants.ts [hunk 1]
```diff
@@ -21,20 +21,20 @@ export interface GaugeTheme {
...
+  lineStrokeSmall: 1,
   minFontSize: 22,
   minLineWidth: 24,
-  valueColor: `${InfluxColors.Graphite}`,
   needleColor0: `${InfluxColors.Wolf}`,
   needleColor1: `${InfluxColors.Smoke}`,
+  smallLineCount: 10,
+  tickSizeLarge: 18,
+  tickSizeSmall: 9,
+  valueColor: `${InfluxColors.Graphite}`,
```
Comment (TCL735) [inline src/visualization/types/Gauge/constants.ts:37]: alphabetizing only

File: src/visualization/types/Gauge/constants.ts [hunk 2]
```diff
@@ -45,24 +45,27 @@ export const GAUGE_THEME_LIGHT: GaugeTheme = {
...
+  lineStrokeSmall: 1,
   minFontSize: 22,
   minLineWidth: 24,
-  valueColor: `${InfluxColors.White}`,
   needleColor0: `${InfluxColors.Smoke}`,
   needleColor1: `${InfluxColors.White}`,
+  smallLineCount: 10,
+  tickSizeLarge: 18,
+  tickSizeSmall: 9,
+  valueColor: `${InfluxColors.White}`,
```
Comment (TCL735) [inline src/visualization/types/Gauge/constants.ts:61]: alphabetizing only

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 53 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=2022)

**Review by russorat — APPROVED** [review]
LGTM
