### PR TITLE
fix: broken template

### LINKED ISSUE #3360: Notebooks: Adding a task panel or opening up a task Notebook template result in an error
When I try to add a task panel or open a Schedule a Task notebook template, I get an error. 

https://images.zenhubusercontent.com/279622976/b050c10b-b66a-41f7-af6d-a1201b716b7d/screen_recording_2021_12_02_at_1_53_08_pm.mov

### PR DESCRIPTION
**Pull request by drdelambre**
Closes #3360

### CODE REVIEW

File: src/flows/pipes/Schedule/view.tsx [hunk 1]
```diff
@@ -228,15 +228,13 @@ const Schedule: FC<PipeProp> = ({Context}) => {
...
-    if (data.task.length) {
-      return taskText !== data.task[0].flux
-    }
-    return false
-  }, [taskText, data?.task?.flux])
+  let lastTask
+  if (data.task?.id) {
+    lastTask = data.task
+  } else if (data.task?.length) {
+    lastTask = data.task[0]
```
Comment (asalem1) [inline src/flows/pipes/Schedule/view.tsx:235]: wouldn't this need to be `data.task[data.task.length -1]`? if we're getting the last one?

Comment (drdelambre) [reply src/flows/pipes/Schedule/view.tsx:235]: lol i guess that is confusing. i'm referring to the "last created" but it's the first in the list

**Review by asalem1 — APPROVED** [review]

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 60 | :red_circle:
accessibility | 97 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=3361)
