### PR TITLE
fix: update usage dashboard link to new tools

### LINKED ISSUE #5311: Operator Page: OrgOverlay has hard-coded URL to Old Tools
ui/operator/OrgOverlay.tsx contains a link to the Usage Dashboard for a given org.  That link is hardcoded to Old Tools on line 111:

> href={`https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/0649b03029c49000?vars%5Borgid%5D=${orgID}`}

This URL should be replaced with either a relative reference or hard-coded new Tools URL: Check with e-commerce team about what this setting should be.

### PR DESCRIPTION
**Pull request by david-rusnak**
Closes #5311 

Changes link to usage dashboard from operators page to new tools. Users will now be sent to the correct usage dashboard in new tools.

### Checklist

Authors and Reviewer(s), please verify the following:

- [x] A PR description, regardless of the triviality of this change, that communicates the value of this PR
- [x] [Well-formatted conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/) that provide context into the change
- [x] Documentation updated or issue created (provide link to issue/PR)
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] Feature flagged, if applicable

### CODE REVIEW

File: src/operator/OrgOverlay.tsx [hunk 1]
```diff
@@ -108,7 +108,7 @@ const OrgOverlay: FC = () => {
                       text="View Usage Dashboard"
                       target={LinkTarget.Blank}
                       className="overlay-button--link"
-                      href={`https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/0649b03029c49000?vars%5Borgid%5D=${orgID}`}
+                      href={`https://us-east-1-2.aws.cloud2.influxdata.com/orgs/5d59ccc5163fc318/dashboards/0988da0fd78a7003?vars%5Borgid%5D=${orgID}`}
```
Comment (ChitlangeSahas) [inline src/operator/OrgOverlay.tsx:111]: I remember talking in the Friday standup on how the previous tools was hard coded here. Do we want to change the approach?

Otherwise looks good!

**Review by wdoconnell — APPROVED** [review]
LGTM. I'll note here for posterity and to @david-rusnak 's credit that testing this one line required significantly more work. 😺

File: src/operator/OrgOverlay.tsx (hunk 1 above)
Comment (wdoconnell) [reply src/operator/OrgOverlay.tsx:111]: @ChitlangeSahas Correct!  But per AIM, they want us to keep this hardcoded.

Comment (ChitlangeSahas) [reply src/operator/OrgOverlay.tsx:111]: Got it 👍

**Review by ChitlangeSahas — APPROVED** [review]

File: src/operator/OrgOverlay.tsx (hunk 1 above)
Comment (hoorayimhelping) [reply src/operator/OrgOverlay.tsx:111]: doing a code search of `influxdb.aws.influxdata.io` reveals a couple of places in `flows` where this url is hardcoded. I think it might be a good idea to store `https://us-east-1-2.aws.cloud2.influxdata.com` into a variable called `TOOLS_URL`, which is still keeping it hardcoded (rather than based on a config value), but makes it slightly easier to work with.
