### PR TITLE
fix: force null return from global header until all values loaded

### LINKED ISSUE #5526: minified react error #152
Staging environments using Electron (likely cypress) are throwing [minified react error #152](https://reactjs.org/docs/error-decoder.html/?invariant=152&args[]=ce), which is caused when an invocation of `render` does not return anything (including `null`). Appears to be correlated with `multiOrg` flag. 

## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Run tests with multiOrg flag enabled in Electron (e.g. cypress).

**Expected behavior:**
No error

**Actual behavior:**
Minified react error #152

**Visual Proof:**

## About your environment

**Environment info:**
Electron

### PR DESCRIPTION
**Pull request by wdoconnell**
Closes #5526

This fixes a bug where globalheader could throw minified react error #152 - `Nothing was returned from render.` This was identified in Electron environments in staging, but I'm able to reproduce it elsewhere by manually setting values associated with the user's identity to `undefined`.

The cause of the issue is that the expressions used for checking whether the data associated with the header and user avatar weren't type cast to `boolean`.

When at least one element in _both_ the guards against loading the avatar and dropdown was `undefined` - for example, when the optional chaining operator cast the value to `undefined` because the property didn't exist yet - `shouldLoadGlobalHeader` also evaluated to undefined, a value that the functional component can't return, throwing an error before the user-associated data loaded.

The fix type casts to `boolean` each of the guards against loading the dropdowns; avatar; and header, and explicitly forces a `null` return if the header should not yet load.

Pre-Fix: Error thrown before header loads
--
Screen Shot 2022-08-24 at 4 18 38 PM

Post-Fix: Header only loads after all values present
--
Pre-load - some values still `undefined`
Screen Shot 2022-08-24 at 4 47 04 PM

Post-load
Screen Shot 2022-08-24 at 4 47 49 PM

### Checklist

Authors and Reviewer(s), please verify the following:

- [X] A PR description, regardless of the triviality of this change, that communicates the value of this PR
- [X] [Well-formatted conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/) that provide context into the change
- [X] Documentation updated or issue created (provide link to issue/PR)
- [X] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [X] Feature flagged, if applicable - `multiOrg`

### CODE REVIEW

**Review by ChitlangeSahas — APPROVED** [review]

File: src/identity/components/GlobalHeader/GlobalHeader.tsx [hunk 1]
```diff
@@ -77,42 +77,44 @@ export const GlobalHeader: FC = () => {
     }
   }, [orgsList])
 
-  const shouldLoadDropdowns = activeOrg?.id && activeAccount?.id
-  const shouldLoadAvatar =
-    user?.firstName && user?.lastName && user?.email && org?.id
-  const shouldLoadGlobalHeader = shouldLoadDropdowns || shouldLoadAvatar
+  const shouldLoadDropdowns = !!(activeOrg?.id && activeAccount?.id)
+  const shouldLoadAvatar = !!(
```
Comment (hoorayimhelping) [inline src/identity/components/GlobalHeader/GlobalHeader.tsx:81]: if we're already wrapping this boolean cast in parens, might as well do something like

```ts
Boolean(activeOrg?.id && activeAccount?.id)
```

which does the same thing as

```ts
!!(activeOrg?.id && activeAccount?.id)
```

but is generally more explicit and clear to people who aren't super familiar with JavaScript

**Review by hoorayimhelping — APPROVED** [review]
Have a minor nitpick/suggestion. But you don't have to hold up this PR for it.

File: src/identity/components/GlobalHeader/GlobalHeader.tsx (hunk 1 above)
Comment (wdoconnell) [reply src/identity/components/GlobalHeader/GlobalHeader.tsx:81]: No, I like your change - there's a mix of both `!!` and `Boolean` in the codebase, but `Boolean` is definitely clearer. Will change.
