### PR TITLE
fix: initial validation check

### LINKED ISSUE #980: Annotations: Non blocking cleanup work
### Background
Cleanup work and tech debt that needs to get done but shouldn't block release

### Things to do
- [x] Make form validation function a real thing
- [x] Make show annotations on by default and enable 1 click annotations off by default

### PR DESCRIPTION
**Pull request by ShmuelLotman**
Closes #980 

Adds initial validation that just checks that a message and summary/time is included. Will eventually morph as we understand more about how we want to validate incoming forms

### CODE REVIEW

**Comment by hercules-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 28 | :red_circle:
accessibility | 96 | :green_circle:
best-practices | 93 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :question:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?vars%5Blighthouse_score_branch%5D=1115)

File: src/annotations/components/annotationForm/AnnotationForm.tsx [hunk 1]
```diff
@@ -32,6 +33,10 @@ export const AnnotationForm: FC<Props> = (props: Props) => {
   const [startTime, setStartTime] = useState(props.startTime)
   const [message, setMessage] = useState('')
 
+  const isValidAnnotationForm = ({message, startTime}): boolean => {
+    return message.length && startTime
```
Comment (hoorayimhelping) [inline src/annotations/components/annotationForm/AnnotationForm.tsx:37]: very nice 👌

**Review by hoorayimhelping — APPROVED** [review]
good work. thank you, thank you! time to put annotations to bed!
