### PR TITLE
test: attempt to fix flakiness by alternating commands and assertions

### LINKED ISSUE #2334: Flaky Test: can edit an annotation for the single stat + line graph
The test `can edit an annotation for the single stat + line graph` is flaky. 

```
Issue: "the element has been detached from the DOM"
```

We determined that this is probably related to the z-index issue which is being worked on

Example: 
- https://app.circleci.com/pipelines/github/influxdata/monitor-ci/3899/workflows/112c9ad9-b78a-4399-91b2-aff66aff6f26/jobs/64203
- https://app.circleci.com/pipelines/github/influxdata/monitor-ci/3902/workflows/dc2ae30d-901e-4d08-8ace-be813aca2cb0/jobs/64507
- (xy graph, but same failure): https://app.circleci.com/pipelines/github/influxdata/monitor-ci/3965/workflows/a10a4a2c-9297-4f4b-8034-e31c4dbaedf8/jobs/68853
- https://app.circleci.com/pipelines/github/influxdata/monitor-ci/3979/workflows/018c3c7a-b15c-4670-a642-90c60f83c90d/jobs/70295
- https://app.circleci.com/pipelines/github/influxdata/monitor-ci/4118/workflows/5f6d490b-e169-49d9-ae07-c02564091f60/jobs/80223

### PR DESCRIPTION
**Pull request by hoorayimhelping**
Closes #2334 

>There is another way to fix our flaky test. Whenever you write a longer test, **we recommend alternating commands with assertions.**

https://docs.cypress.io/guides/core-concepts/retry-ability#Alternate-commands-and-assertions

### CODE REVIEW

File: cypress/e2e/util/annotationsSetup.ts [hunk 1]
```diff
@@ -99,11 +99,15 @@ export const startEditingAnnotation = (cy: Cypress.Chainable) => {
 export const editAnnotation = (cy: Cypress.Chainable) => {
   startEditingAnnotation(cy)
 
-  cy.getByTestID('edit-annotation-message').should('have.length.of.at.least', 1)
-  cy.getByTestID('edit-annotation-message').clear()
-  cy.getByTestID('edit-annotation-message').type('lets edit this annotation...')
+  cy.getByTestID('edit-annotation-message')
+    .should('have.length.of.at.least', 1)
+    .clear()
+    .should('have.length.of.at.least', 1)
```
Comment (joelfried) [inline cypress/e2e/util/annotationsSetup.ts:105]: I'm confused by this assertion and am hoping you can clarify.  What exactly does clear() do on the line above if the message is still of length one afterwards?

I'd have naively expected the message length to be zero since it was cleared out.

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 59 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=2336)

File: cypress/e2e/util/annotationsSetup.ts (hunk 1 above)
Comment (hoorayimhelping) [reply cypress/e2e/util/annotationsSetup.ts:107]: @joelfried `clear()` empties the contents of the textbox. the `should('have.length.of.at.least', 1)` is asserting that there is at least one textbox with the testID of `edit-annotation-message` that is being rendered in the DOM. 

we don't technically need to do the `clear()` to edit the contents, but it's more representative of human behavior

Comment (joelfried) [reply cypress/e2e/util/annotationsSetup.ts:107]: Gotcha.  I've gone with using `should('be.visible')` in my tests for similar effects.  I think the juxtaposition with the `clear()` put me in a different frame of mind.  Thanks for clarifying!

File: cypress/e2e/util/annotationsSetup.ts [hunk 2]
```diff
@@ -99,11 +99,15 @@ export const startEditingAnnotation = (cy: Cypress.Chainable) => {
...
+    .type('lets edit this annotation...')
```
[the remark this answers is not in the document]
Comment (hoorayimhelping) [reply cypress/e2e/util/annotationsSetup.ts:108]: >it terms of separating out get's for retry-ability, better to do

@jrenee42 I hope this doesn't come off as flippant but: [citation needed]. I tried to back up why I did this with documentation that says the `command / assertion` pattern helps prevent flakiness. I think I remember seeing somewhere in Cypress docs say that chaining without assertions is bad, but can you link to it please?

>also; the second length check on line 105 should fail; you just cleared it!
`should('have.length')` is not about the content, it's about the number of elements in the DOM: https://docs.cypress.io/guides/references/assertions#Length

[the remark this answers is not in the document]
Comment (jrenee42) [reply cypress/e2e/util/annotationsSetup.ts:108]: > > it terms of separating out get's for retry-ability, better to do
> 
> @jrenee42 I hope this doesn't come off as flippant but: [citation needed]. I tried to back up why I did this with documentation that says the `command / assertion` pattern helps prevent flakiness. I think I remember seeing somewhere in Cypress docs say that chaining without assertions is bad, but can you link to it please?
> 
> > also; the second length check on line 105 should fail; you just cleared it!
> 
> `should('have.length')` is not about the content, it's about the number of elements in the DOM: https://docs.cypress.io/guides/references/assertions#Length

ah, ok! thanks for pointing to the docs on that one.

**Review by jrenee42 — APPROVED** [review]
