### PR TITLE
fix: handle no bucket selected

### LINKED ISSUE #3244: notebook sharing: link breaks if you flip from presentation to non-presentation mode
Steps to reproduce:
1. Build a notebook.
2. Put into presentation mode.
3. Generate a share link.
4. Click on link - will display fine
5. Put notebook in non-presentation mode.
6. Click on share link - will get InfluxDB error:
```
react-dom.production.min.js:198 TypeError: Cannot read properties of undefined (reading 'name')
    at button (/static/27.78a3fc3d4b.js:2)
    at /static/24.832b4d5d33.js:2
    at Wo (/static/24.832b4d5d33.js:2)
    at yi (/static/24.832b4d5d33.js:2)
    at ki (/static/24.832b4d5d33.js:2)
    at Na (/static/24.832b4d5d33.js:2)
    at ja (/static/24.832b4d5d33.js:2)
    at As (/static/24.832b4d5d33.js:2)
    at Cs (/static/24.832b4d5d33.js:2)
    at vs (/static/24.832b4d5d33.js:2)
ra @ react-dom.production.min.js:198
```

### PR DESCRIPTION
**Pull request by genehynson**
Closes #3244

Previously the shared notebook would crash if no bucket was selected in query builder. This adds a safe guard so we show "No bucket selected"  instead

image

### CODE REVIEW

File: src/flows/pipes/QueryBuilder/readOnly.tsx [hunk 1]
```diff
@@ -37,7 +37,9 @@ const QueryBuilder: FC<PipeProp> = ({Context}) => {
                         icon={IconFont.BucketSolid}
                         status={ComponentStatus.Disabled}
                       >
-                        {data.buckets[0].name ?? 'No Bucket Selected'}
+                        {!!data.buckets.length && data.buckets[0].name
+                          ? data.buckets[0].name
+                          : 'No Bucket Selected'}
```
Comment (asalem1) [inline src/flows/pipes/QueryBuilder/readOnly.tsx:42]:
```suggestion
                        {!!data?.buckets?.length && data?.buckets?.[0]?.name
                          ? data.buckets[0].name
                          : 'No Bucket Selected'}
```

**Review by drdelambre — APPROVED** [review]

**Review by asalem1 — APPROVED** [review]
nit:

File: src/flows/pipes/QueryBuilder/readOnly.tsx (hunk 1 above)
Comment (genehynson) [reply src/flows/pipes/QueryBuilder/readOnly.tsx:42]: I'm pretty sure `data` and `data.buckets` will always exist...but sure better to be safe than sorry :)

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 61 | :yellow_circle:
accessibility | 97 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 93 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=3252)
