### PR TITLE
fix: trim url and add error for spaces in between characters in url

### LINKED ISSUE #697: Template Uploader Says Valid URL But Fails Upload
When uploading a template via URL the URL input shows that the input is valid, but then fails on upload.

### PR DESCRIPTION
**Pull request by ShmuelLotman**
Closes #697 

This PR introduces an error message for the template url uploader when there is a space in between characters in the url and it also trims the url before submission.

- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

### CODE REVIEW

File: src/templates/utils/index.ts [hunk 1]
```diff
@@ -169,6 +169,10 @@ export const validateTemplateURL = (url): string => {
     return "We can't use that URL"
   }
 
+  if (cleanUrl.includes(' ')) {
+    return 'URL cannot contain spaces'
```
Comment (hoorayimhelping) [inline src/templates/utils/index.ts:173]: the first thing is, i think this would be easier to follow if it was moved to right under where `cleanUrl` is defined. think about the flow of this function. if the template has a space in it, we don't care if it's a community or a correct file type, it's immediately wrong and unparse-able. it's a stronger indicator and so should come first.

the other thing is, the message is kind of mechanical compared to the other messages in this file, which are a little bit more conversational.

maybe something as simple as adding `the` or `your` and dropping the `cannot`

>"Your URL can't contain spaces"

**Review by hoorayimhelping — CHANGES_REQUESTED** [review]
minorish nits but worth tweaking just for consistency's sake

File: src/templates/containers/CommunityTemplatesIndex.tsx [hunk 2]
```diff
@@ -259,10 +259,11 @@ class UnconnectedCommunityTemplatesIndex extends Component<Props, State> {
   }
 
   private handleTemplateChange = event => {
-    const validationMessage = validateTemplateURL(event.target.value)
+    const trimmedValue = event.target.value.trim()
```
Comment (hoorayimhelping) [inline src/templates/containers/CommunityTemplatesIndex.tsx:262]: naming nit: `value` is a vague name. `trimmedUrl` is much more self-documenting.

File: src/templates/utils/index.ts [hunk 3]
```diff
@@ -146,6 +146,10 @@ export const validateTemplateURL = (url): string => {
   */
   const cleanUrl = url.trim().split('?')[0]
 
+  if (cleanUrl.includes(' ')) {
+    return `Your URL can't contain spaces`
```
Comment (hoorayimhelping) [inline src/templates/utils/index.ts:150]: context nit: a string wrapped in \`backticks\` implies there will be string interpolation. Better to use double quotes here, which in our codebase are only used when there's a single quote in the string.

**Review by hoorayimhelping — APPROVED** [review]
looks good - some minor naming nitpicks
