### PR TITLE
fix: calculate the correct heights for the header and rows in SimpleTable

### LINKED ISSUE #5239: SimpleTable: rows of data are hidden in overflow and cannot be viewed
https://user-images.githubusercontent.com/10736577/181654313-2fc4c16d-60db-4279-8aa4-f975f378da5c.mp4

### PR DESCRIPTION
**Pull request by TCL735**
Closes #5239  

- Instead of using old and incorrect values for the header and row heights of the SimpleTable, calculate them.
- This allows SimpleTable to make all rows visible without relying on vertical scrolling.
- **_There must be enough vertical space to fit at least 25% of the height of the next row for that row to render._**

https://user-images.githubusercontent.com/10736577/181658050-05cc838a-e5a1-4823-95e4-89a8c8eaeb32.mp4

### CODE REVIEW

File: src/visualization/types/SimpleTable/PagedTable.tsx [hunk 1]
```diff
@@ -232,8 +234,31 @@ const PagedTable: FC<Props> = ({result, properties}) => {
...
   } = useContext(PaginationContext)
   const [height, setHeight] = useState(0)
+  const [headerHeight, setHeaderHeight] = useState(0)
+  const [rowHeight, setRowHeight] = useState(0)
   const ref = useRef()
 
+  if (headerHeight === 0) {
+    const calculatedHeaderHeight =
+      document.querySelector<HTMLElement>(`#${pagedTableHeaderId}`)
+        ?.offsetHeight ?? 0
```
Comment (hoorayimhelping) [inline src/visualization/types/SimpleTable/PagedTable.tsx:244]: Something to consider when using `querySelector` vs `ref`s: https://stackoverflow.com/a/69260293/92446. Not sure how feasible it is to use refs here, or if one is better than the other.

File: src/visualization/types/SimpleTable/PagedTable.tsx [hunk 2]
```diff
@@ -274,8 +299,8 @@ const PagedTable: FC<Props> = ({result, properties}) => {
   }, []) // eslint-disable-line react-hooks/exhaustive-deps
 
   const size = useMemo(() => {
-    return measurePage(result, offset, height)
-  }, [result, offset, height])
+    return measurePage(result, offset, height, headerHeight, rowHeight)
+  }, [result, offset, height, headerHeight, rowHeight])
```
Comment (hoorayimhelping) [inline src/visualization/types/SimpleTable/PagedTable.tsx:303]: should `measurePage` be included in the dependency array?

File: src/visualization/types/SimpleTable/PagedTable.tsx [hunk 3]
```diff
@@ -285,8 +310,8 @@ const PagedTable: FC<Props> = ({result, properties}) => {
   }, [size]) // eslint-disable-line react-hooks/exhaustive-deps
 
   useEffect(() => {
-    setMaxSize(measurePage(result, 0, height))
-  }, [height, result]) // eslint-disable-line react-hooks/exhaustive-deps
+    setMaxSize(measurePage(result, 0, height, headerHeight, rowHeight))
+  }, [result, height, headerHeight, rowHeight]) // eslint-disable-line react-hooks/exhaustive-deps
```
Comment (hoorayimhelping) [inline src/visualization/types/SimpleTable/PagedTable.tsx:314]: should `setMaxSize` and `measurePage` be included in the dependency array?

**Review by hoorayimhelping — APPROVED** [review]
Nice find; Works for me, but a couple of comments about implementation details

File: src/visualization/types/SimpleTable/PagedTable.tsx (hunk 1 above)
Comment (TCL735) [reply src/visualization/types/SimpleTable/PagedTable.tsx]: Yeah, `useRef` is easier. i wouldn't need `ids` at all even though this calculation is done only once. It's a minor improvement, but still an improvement!

File: src/visualization/types/SimpleTable/PagedTable.tsx (hunk 2 above)
Comment (TCL735) [reply src/visualization/types/SimpleTable/PagedTable.tsx:309]: No, the linter doesn't complain about `measurePage`. There is only one `measurePage` in the whole module, as it is a constant. That's probably the reason why the linter doesn't complain about it.

File: src/visualization/types/SimpleTable/PagedTable.tsx (hunk 3 above)
Comment (TCL735) [reply src/visualization/types/SimpleTable/PagedTable.tsx:320]: See above for `measurePage`.

For `setMaxSize`, it's not needed since `setMaxSize` is the setter from a `useState`. As far as I am aware, the setter doesn't change and would make no difference in a dependency array.
