### PR TITLE
fix(influxql): add selected tag keys to `SELECT` statement

### LINKED ISSUE #6715: InfluxQL UI: missing tag key in returned table
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Turn on feature flag `influxqlUI`, `showOldDataExplorerInNewIOx`, and `schemaComposition`
2. Create DBRP mappings in your org ([instructions](https://github.com/influxdata/idpe/issues/17205))
3. Go to the new Data Explorer page, select a database / retention policy, a measurement, a field, and a tag
4. Click "Run"

**Expected behavior:**
Expect to see the selected tag column in the returned table

**Actual behavior:**
Missing the selected tag column

**Visual Proof:**

https://github.com/influxdata/ui/assets/14298407/7c163da3-48fa-4b92-bb98-6fa9efeb72a4

Screen Shot 2023-06-05 at 5 03 43 PM

### PR DESCRIPTION
**Pull request by appletreeisyellow**
Closes #6715

This PR adds the selected tag keys to the `SELECT` statement so that the tag keys show up as a column in the result table

## Before

https://github.com/influxdata/ui/assets/14298407/7c163da3-48fa-4b92-bb98-6fa9efeb72a4

## After

https://github.com/influxdata/ui/assets/14298407/d35b8bcb-c4e9-497f-a723-b93e15fd14ea

### Checklist

Authors and Reviewer(s), please verify the following:

- [x] A PR description, regardless of the triviality of this change, that communicates the value of this PR
- [x] [Well-formatted conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/) that provide context into the change
- [x] Documentation updated or issue created (provide link to issue/PR)
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] Feature flagged, if applicable

### CODE REVIEW

File: src/languageSupport/languages/influxql/connection.ts [hunk 1]
```diff
@@ -21,6 +22,26 @@ import {compositionEnded} from 'src/shared/copy/notifications'
 import {groupedTagValues} from 'src/languageSupport/languages/agnostic/utils'
 import {isFlagEnabled} from 'src/shared/utils/featureFlag'
 
+/*
```
Comment (blegesse-git) [inline src/languageSupport/languages/influxql/connection.ts:25]: did you mean to leave this comment here?

**Review by blegesse-git — APPROVED** [review]
looks good to me

File: src/languageSupport/languages/influxql/connection.ts (hunk 1 above)
Comment (appletreeisyellow) [reply src/languageSupport/languages/influxql/connection.ts:25]: Yeah, just to make it easier to understand what the function does

Comment (helenosheaa) [reply src/languageSupport/languages/influxql/connection.ts:25]: fwiw i find writing a utils test for a helper function a good way to demonstrate what a function does / prevents people misinterpreting and breaking it

Comment (appletreeisyellow) [reply src/languageSupport/languages/influxql/connection.ts:25]: Good call! I'll move that into a util with a unit test

**Review by helenosheaa — APPROVED** [review]
nice!
