### PR TITLE
fix: reverts to react-markdown, fixes template bug

### LINKED ISSUE #257: Update Plugins page to use the new markdown library
For the fix for this bug: https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/idpe/8810, I pulled in the new markdown library called Marked.js `https://marked.js.org/`.

After fixing the bug I realized we are using our old `React Markdown` library to render markdown for plugins under Data/Sources. For example: Telegraph Plugins.

I tried rendering `marked` for this but it doesn't render react components within the markdown. So for the code blocks with the backticks in the readME and the markdown, we are currently rendering a react component for displaying code snippet with a scrollbar and `Copy to Clipboard` button. But for the marked library we are unable to render such React components within the markdown.

This story is so that we can implement using the new library for plugins and the React Markdown library from our project.

### PR DESCRIPTION
**Pull request by genehynson**
Closes #257, #456

I was unable to find a way to use the Marked.js library to render React components around code blocks like we were with the React-Markdown library. So, I went back to issue https://github.com/influxdata/idpe/issues/8810 which led us to replace React-Markdown with Marked to see if I could fix that issue using React-Markdown instead. Turns out I was able to by implementing an htmlParser and disabling `escapeHtml`. 

I couldn't find away around adding the `html-to-react` package. However, it is much smaller (57kb) compared to `Marked.js` (267kb).

Image rendering rules (e2e tests included for these):
- OSS: render images ✅ 
- Cloud: do not render images ❌ 

Details:
+ adds htmlParser for react-markdown to handle rendering unsafe img tags
+ disables escapeHtml for react-markdown to fix the rendering of the
details tag
+ removes marked package, adds html-to-react package for htmlParser
support
+ adds e2e tests for cloud & oss

Community Templates README:

CommunityTemplateReadme

Data/Sources/Plugins:

Screen Shot 2020-12-17 at 5 00 09 PM

Dashboards / Note (OSS):

Screen Shot 2020-12-18 at 3 44 54 PM

Dashboards / Note (Cloud):

Screen Shot 2020-12-18 at 4 00 23 PM

- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

### CODE REVIEW

**Comment by TCL735** [comment]
I am going to be off for a couple of weeks. Adding team/ui to the reviewers so that someone can take a look at this while I am out.

**Comment by hercules-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 26 | :red_circle:
accessibility | 65 | :yellow_circle:
best-practices | 87 | :green_circle:
seo | 80 | :yellow_circle:
pwa | 22 | :red_circle:

**Comment by genehynson** [comment]
@TCL735 if you're back from pto, would you mind taking a look?

File: src/shared/constants/index.ts [hunk 1]
```diff
@@ -132,3 +132,6 @@ export const LEGEND_ORIENTATION_THRESHOLD_DEFAULT = 10
 
 export const QUERY_BUILDER_MODE = 'builder'
 export const SCRIPT_EDITOR_MODE = 'advanced'
+
+export const MARKDOWN_UNSUPPORTED_IMAGE =
```
Comment (hoorayimhelping) [inline src/shared/constants/index.ts:136]: it seems like this is obvious from context but just so it's clear: the business rule is we don't support images in markdown on cloud, but they're totally okay in oss environments. if we start integrating ui into OSS, this will probably become relevant again.

File: src/templates/components/CommunityTemplateReadme.tsx [hunk 2]
```diff
@@ -34,9 +31,6 @@ class CommunityTemplateReadmeUnconnected extends Component<Props> {
     return (
       <MarkdownRenderer
         text={readme}
-        cloudRenderers={{
-          image: cloudImageRenderer,
-        }}
```
Comment (hoorayimhelping) [inline src/templates/components/CommunityTemplateReadme.tsx:39]: is this the bug? what was the main issue?

File: src/shared/constants/index.ts (hunk 1 above)
Comment (genehynson) [reply src/shared/constants/index.ts:136]: exactly! Let me add that to the PR description to make sure it's clear

File: src/templates/components/CommunityTemplateReadme.tsx (hunk 2 above)
Comment (genehynson) [reply src/templates/components/CommunityTemplateReadme.tsx:39]: The main issue was that we needed to add the flag `escapeHtml={false}` to ReactMarkdown component

**Review by Palakp41 — APPROVED** [review]
Lgtm

File: src/shared/components/views/MarkdownRenderer.tsx [hunk 3]
```diff
@@ -22,43 +53,20 @@ export const MarkdownRenderer: FC<Props> = ({
...
 
+  // load images locally to your heart's content. caveat emptor
   return (
-    <div
-      className={className}
-      dangerouslySetInnerHTML={{
-        __html: marked(text),
-      }}
-    ></div>
+    <ReactMarkdown source={text} className={className} escapeHtml={false} />
```
[the remark this answers is not in the document]
Comment (genehynson) [reply src/shared/components/views/MarkdownRenderer.tsx:70]: You know what I saw an issue that they broke the `escapeHtml` flag in one of the versions. I wonder if maybe that was the version you were using? Who knows though. It was certainly an annoying bug 😆
