### PR TITLE
fix: add bucket prop back to execute query page

### LINKED ISSUE #5174: firstMile: InfluxCLI Onboarding - Add bucket prop to Execute Query page
Need to add the `bucket` prop into the `Execute Query` page so that the flux script bucket name can change dynamically based on which bucket the user selects.

### PR DESCRIPTION
**Pull request by david-rusnak**
Closes #5174

Adds `bucket` prop back to `Execute Query` page so that the flux script can update the users bucket name dynamically.

### Checklist

Authors and Reviewer(s), please verify the following:

- [x] A PR description, regardless of the triviality of this change, that communicates the value of this PR
- [x] [Well-formatted conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/) that provide context into the change
- [x] Documentation updated or issue created (provide link to issue/PR)
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] Feature flagged, if applicable

### CODE REVIEW

File: src/homepageExperience/components/steps/cli/ExecuteQuery.tsx [hunk 1]
```diff
@@ -8,8 +8,15 @@ const logCopyCodeSnippet = () => {
...
-  const query = `influx query 'from(bucket:"sample-bucket") |> range(start:-10m)' --raw`
+type OwnProps = {
+  bucket: string
+}
+
+export const ExecuteQuery = (props: OwnProps) => {
+  const {bucket} = props
+  const query = `influx query 'from(bucket:"${
+    bucket === '<BUCKET>' ? 'sample-bucket' : bucket
+  }") |> range(start:-10m)' --raw`
```
Comment (hoorayimhelping) [inline src/homepageExperience/components/steps/cli/ExecuteQuery.tsx:19]: it'd probably be cleaner and easier to follow if this expression to get the proper bucket name was stored into a variable.

```ts
const bucketName = bucket === '<BUCKET>' ? 'sample-bucket' : bucket
const query = `influx query 'from(bucket:"${bucketName}") |> range(start:-10m)' --raw`
```

**Review by hoorayimhelping — APPROVED** [review]
lgtm, but have a minor suggestion about making the query a little easier to follow
