### PR TITLE
fix: added default token description

### LINKED ISSUE #2199: Tokens with no description do not show up in the token selector for the client libraries page
I noticed that the tokens without descriptions are showing up on the client libraries page with an empty description. We should use the default api token description text here.

image

### PR DESCRIPTION
**Pull request by blegesse-git**
Closes #2199 

tokens without descriptions are showing up on the client libraries page with an empty description. 
Before: 
before
After: 
after
pr fixes this issue by importing `DEFAULT_TOKEN_DESCRIPTION` and using it in place of no name tokens.

### CODE REVIEW

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 60 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=2290)

File: src/writeData/components/WriteDataHelperTokens.tsx [hunk 1]
```diff
@@ -32,6 +33,11 @@ const WriteDataHelperTokens: FC = () => {
     getAll<Authorization>(state, ResourceType.Authorizations)
   )
   const {token, changeToken} = useContext(WriteDataDetailsContext)
+  tokens.map(t => {
+    t.description.length === 0
```
Comment (ChitlangeSahas) [inline src/writeData/components/WriteDataHelperTokens.tsx:37]: Like we spoke, as long as `t.description` is never undefined, this looks good!

**Review by ChitlangeSahas — APPROVED** [review]

**Review by hoorayimhelping — APPROVED** [review]
