### PR TITLE
fix: add keys to BucketMeta components that are rendered in lists

### LINKED ISSUE #2612: React key warning in `BucketCardMeta`
```Warning: Each child in a list should have a unique "key" prop.

Check the render method of `BucketCardMeta`. See https://fb.me/react-warning-keys for more information.
    in span (created by BucketCardMeta)
    in BucketCardMeta (created by ConnectFunction)
    in ConnectFunction (created by BucketCard)
    in div (created by FlexBox)
    in FlexBox (created by ResourceCard)
    in div (created by ResourceCard)
    in ResourceCard (created by ResourceCard)
    in ResourceCard (created by BucketCard)
    in BucketCard (created by Context.Consumer)
    in withRouter(BucketCard) (created by BucketList)
    in div (created by ResourceListBody)
    in ResourceListBody (created by BucketList)
    in div (created by ResourceList)
    in ResourceList (created by ResourceList)
    in ResourceList (created by BucketList)
    in BucketList (created by Context.Consumer)
    in withRouter(BucketList) (created by ```

### PR DESCRIPTION
**Pull request by hoorayimhelping**
Closes #2612

Fixes key prop warning by rendering components directly instead of in an array

### CODE REVIEW

**Review by ChitlangeSahas — APPROVED** [review]

**Review by TCL735 — APPROVED** [review]

File: src/buckets/components/BucketCardMeta.tsx [hunk 1]
```diff
@@ -56,9 +56,14 @@ const BucketCardMeta: FC<Props> = ({bucket, notify}) => {
...
 
-  const bucketInfo = CLOUD
-    ? [persistentBucketMeta, schemaBlock]
-    : [persistentBucketMeta]
+  const bucketInfo = CLOUD ? (
+    <>
+      {persistentBucketMeta}
+      {schemaBlock}
+    </>
+  ) : (
```
Comment (jrenee42) [inline src/buckets/components/BucketCardMeta.tsx:64]: has this been tested when cloud is negative?
just that the second clause is not in curly braces.

want to be extra sure

**Review by jrenee42 — CHANGES_REQUESTED** [review]

File: src/buckets/components/BucketCardMeta.tsx (hunk 1 above)
Comment (hoorayimhelping) [reply src/buckets/components/BucketCardMeta.tsx]: @jrenee42 

It _should_ be fine, since it's doing a variable assignment and the assigned variable (`bucketInfo`) is rendered using curly braces.

But this is a good point. I've actually tweaked the 'solution' to be less of change. I just added `key` props to the two components, rather than changing how they're rendered. Fixes the problems and keeps things similar to the way they were originally authored.

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 55 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=2613)

**Review by jrenee42 — APPROVED** [review]
