### PR TITLE
fix: Pagination jump

### LINKED ISSUE #1884: SimpleTable: Pagination jumping tabs
When viewing the Table in notebooks, which is a `SimpleTable` component. The pagination jumps when one starts at the very last page and click on any other page or the left button. 

#### Example 

https://slack-files.com/T02GAR81Y-F026V9KJ5DK-13dc36c441

### PR DESCRIPTION
**Pull request by mtian725**
Closes #1884

Pagination jumping bug fixed. Solution involves calculating the size, comparing it to the maxSize, and replacing it if it is bigger. 

Also, so small calculation for size (line 45 in PagedTable.tsx). Fix does not change anything, but fixes the math in case it is important in the future.

#### Before
Screen Shot 2021-07-02 at 1 29 58 PM

**101 should be 100**

#### After
Screen Shot 2021-07-02 at 1 30 56 PM

## Example
https://slack-files.com/T02GAR81Y-F027BGXJD4Z-41e69a30a6

### CODE REVIEW

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 55 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=master)

File: src/visualization/types/SimpleTable/PagedTable.tsx [hunk 1]
```diff
@@ -42,7 +42,7 @@ const measurePage = (
   let lastSignature
   let signature
 
-  while (rowIdx <= result.table.length) {
+  while (rowIdx < result.table.length) {
```
Comment (genehynson) [inline src/visualization/types/SimpleTable/PagedTable.tsx:45]: nice. does this fix the 2 records on the last page issue?

**Review by genehynson — APPROVED** [review]
thanks for jumping on this!

**Review by genehynson — COMMENTED** [review]
actually could we add a cypress test for this? Should be pretty easy. You could just add a couple lines to the end of [this test](https://github.com/influxdata/ui/blob/master/cypress/e2e/shared/simpleTable.test.ts#L193) to click a page # and make sure it actually ends up on the correct page #

File: src/visualization/types/SimpleTable/PagedTable.tsx (hunk 1 above)
Comment (mtian725) [reply src/visualization/types/SimpleTable/PagedTable.tsx:45]: Yes. The before and after images has to do with that issue.

File: cypress/e2e/shared/simpleTable.test.ts [hunk 2]
```diff
@@ -192,4 +192,89 @@ describe('simple table interactions', () => {
     cy.getByTestID('table-cell 30').should('not.exist')
     cy.getByTestID('table-cell 31').should('be.visible')
   })
+
+  it('should not jump to an incorrect page when going from the last page to any other page via clicking the page number or left button.', () => {
```
Comment (genehynson) [inline cypress/e2e/shared/simpleTable.test.ts:196]: awesome!

**Review by genehynson — APPROVED** [review]
