### PR TITLE
fix(3706): test query for notebooks alert http endpoint

### LINKED ISSUE #3706: Notebooks(Alert): HTTP Test Alert not being received
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. In AWS EC2 setup a micro instance with a simple express HTTP listener that echos received messages to the console
2. Go to Influxdbv2 UI (note that during this test the feature flag 'notebooksNewEndpoints' was set)
3. Add test data to a bucket
4. Create an Alert Notebook
5. Use the test data to define the query
6. In the alert section choose the HTTP endpoint
7. Provide the URL to the listener in AWS 
8. Click the button 'Test Alert'

**Expected behavior:**

Expected to see the alert message echoed to the AWS EC2 instance console

**Actual behavior:**

No alert message was received. 

Note, that this same endpoint was used in an earlier test of an tradition Alert > Notification Endpoint, and the message was received. 

Note as well, that the Test Alert message was received at a Slack endpoint. 'This is a test notification'.  So this is what I'm expecting to see in the console. 

**Visual Proof:**

NotebookTestAlert01

Note in the above screencast that a notification message had been echoed to the console from an earlier test.  This message was from an endpoint configured in Alerts, and bound to a Threshold check via a Notification Rule.  

## About your environment

**Environment info:**

Tested in K8S-IDPE Remocal. 
Latest UI commit
```
commit a918e664f19a21d33b21fe2c19c7cac8aa01c573 (upstream/master, origin/master, origin/HEAD, master)
Author: Palakp41 <palak@influxdata.com>
Date:   Tue Jan 25 17:16:27 2022 -0800
```
Lates K8S-IDPE commit
```
commit 84c1d4fd7f71ca41759a5f31e3c245c59f3bd4da (HEAD -> master, origin/master, origin/HEAD)
Author: Hercules Mango Churchill <alchemy@influxdata.com>
Date:   Wed Jan 26 02:00:44 2022 +0000
```

**Config:**

**Logs:**

### PR DESCRIPTION
**Pull request by wiedld**
Closes #3706
Issue was that the test Alert, in notebooks, was not functional.

## Done:
* small change to query used for http alerts in notebook. 
     * Update to latest flux syntax, and confirm is working.
* change the running task query to also use the latest flux syntax.
    * confirmed is still working. payload not changed either.
* Confirmed the notebooks task lifecycle still works (for http notifications):
      1. send test alert
      2. export alert as task
      3. task runs, sending notifications
      4. inactivate task --> see that it stop sending notifications.

## Screenshots (proof of functionality)
* test alert
Screen Shot 2022-02-08 at 11 24 52 AM

* outut flux from exported task
Screen Shot 2022-02-08 at 11 16 36 AM

* exported task will run
Screen Shot 2022-02-08 at 11 17 04 AM

* comparison of parsed body (before and after changes). tl;dr payload is the same.
    * before:
    ```
    {
        "_check_id": "d8b1gd7p7565",
        "_check_name": "Notebook Generated Check",
        "_level": "crit",
        "_measurement": "notifications",
        "_message": "Custom for airSensors triggered at 2022-02-08T17:48:08.000000000Z!",
        "_notebook_link": "https://<NAMESPACE>.remocal.influxdev.co/orgs/a767fa74c45001fd/notebooks/5fb6aa11d0dc4000",
        "_notification_endpoint_id": "d8b1gd7p7565",
        "_notification_endpoint_name": "Notebook Generated Endpoint",
        "_notification_rule_id": "d8b1gd7p7565",
        "_notification_rule_name": "Notebook Generated Rule",
        "_source_measurement": "airSensors",
        "_source_timestamp": 1644342488000000000,
        "_start": "2022-02-08T17:48:08Z",
        "_status_timestamp": 1644346088000000000,
        "_stop": "2022-02-08T18:48:08Z",
        "_time": "2022-02-08T18:48:08Z",
        "_type": "custom",
        "_version": 1,
        "co": 0.40518055604716896,
        "sensor_id": "TLM0203"
    }
    ```
    * after:
    ```
    {
        "_check_id": "d8b1gd7p7565",
        "_check_name": "Notebook Generated Check",
        "_level": "crit",
        "_measurement": "notifications",
        "_message": "Custom for airSensors triggered at 2022-02-08T18:14:43.000000000Z!",
        "_notebook_link": "https://<NAMESPACE>.remocal.influxdev.co/orgs/a767fa74c45001fd/notebooks/5fb6aa11d0dc4000",
        "_notification_endpoint_id": "d8b1gd7p7565",
        "_notification_endpoint_name": "Notebook Generated Endpoint",
        "_notification_rule_id": "d8b1gd7p7565",
        "_notification_rule_name": "Notebook Generated Rule",
        "_source_measurement": "airSensors",
        "_source_timestamp": 1644344083000000000,
        "_start": "2022-02-08T18:14:43Z",
        "_status_timestamp": 1644347683000000000,
        "_stop": "2022-02-08T19:14:43Z",
        "_time": "2022-02-08T19:14:43Z",
        "_type": "custom",
        "_version": 1,
        "co": 0.5874328698693015,
        "sensor_id": "TLM0203"
    }
    ```

### CODE REVIEW

File: src/flows/pipes/Notification/endpoints/HTTP/index.ts [hunk 1]
```diff
@@ -72,9 +72,11 @@ export default register => {
...
         .join(', ')
 
-      return `http["endpoint"](url: "${data.url}")(mapFn: (r) => {
-      return {headers: {${_headers}}, data: json["encode"](v: "${TEST_NOTIFICATION}")}
-  })
+      return `http.post(
+        url: "${data.url}",
+        data: json["encode"](v: "${TEST_NOTIFICATION}"),
+        headers: {${_headers}}
+      )
```
Comment (asalem1) [inline src/flows/pipes/Notification/endpoints/HTTP/index.ts:79]: if we make this change here, we should also make it for line 48 in the file above, since the two are related, this being the `testable` version of that (that is to say, it's the one the user tests out by pressing the button, rather than by generating a task)

Comment (wiedld) [reply src/flows/pipes/Notification/endpoints/HTTP/index.ts:79]: good call. updated. Body payload also compared (see readme) --> no change.

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 57 | :red_circle:
accessibility | 97 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=3799)

**Review by asalem1 — APPROVED** [review]
After offlining with Denise, it seems like my initial comment was unfounded. Not opposed to these changes regardless
