### PR TITLE
fix: add missing events for node.js wizard and go wizard

### LINKED ISSUE #4584: firstMile: BUG - Missing events for whether users choose the node.js wizard and the GO wizard
We have an event for if the users click on the Python Wizard Icon. 

However, we do not have events for if the users click on the node.js Wizard Icon and the GO Icon 

Screen Shot 2022-05-16 at 12 25 56 PM

### PR DESCRIPTION
**Pull request by wdoconnell**
Closes  #4584

Eventing in onboarding was set up for users clicking the python wizard icon, but not for users clicking the node wizard or go wizard icons.

Fix adds eventing, and changes function name to be more semantic: e.g., `logPythonWizardClick` instead of `logPythonEvent`

Screen Shot 2022-05-18 at 12 28 45 PM

### CODE REVIEW

File: src/homepageExperience/containers/HomepageContainer.tsx [hunk 1]
```diff
@@ -54,7 +54,15 @@ export const HomepageContainer: FC = () => {
   const squareGridCardSize = '200px'
 
   // events handling
-  const logPythonEvent = () => {
+  const logGoWizardClick = () => {
+    event('firstMile.goWizard.clicked')
+  }
+
+  const logNodeWizardClick = () => {
+    event('firstMile.goWizard.clicked')
```
Comment (ChitlangeSahas) [inline src/homepageExperience/containers/HomepageContainer.tsx:62]: looks good to me!  should this be `firstMile.goWizard.clicked`?

**Review by ChitlangeSahas — APPROVED** [review]

File: src/homepageExperience/containers/HomepageContainer.tsx (hunk 1 above)
Comment (hoorayimhelping) [inline src/homepageExperience/containers/HomepageContainer.tsx:62]: copypasta! (it says `goWizard` not `nodejsWizard`). Also, make sure it's `nodejsWizard` for consistency - all the other event names are `nodejsWizard`, rather than `nodeWizard`)

**Review by hoorayimhelping — APPROVED** [review]
fix up that copy/paste mistake and send it!

File: src/homepageExperience/containers/HomepageContainer.tsx (hunk 1 above)
Comment (wdoconnell) [reply src/homepageExperience/containers/HomepageContainer.tsx]: Thanks! Copypasta fixed.

Comment (wdoconnell) [reply src/homepageExperience/containers/HomepageContainer.tsx]: Made function names consistent.

**Comment by wdoconnell** [comment]
@Luckette Asked for an additional event for the 'More' button to detect when the user isn't using the Go, Python, or NodeJS wizards -- added that in latest commit.

**Review by hoorayimhelping — APPROVED** [review]
