### PR TITLE
fix: fixes most of the windows commands

### LINKED ISSUE #5390: firstMile: InfluxCLI Onboarding - Fix windows commands
We need to update the code snippets based on which operating system the users are using. Mac and linux should be the same but windows needs its own commands.

### PR DESCRIPTION
**Pull request by david-rusnak**
Closes #5390

Displays commands based on which OS the user is using. Now windows commands are correct and the directions are more clear. More work needs to be done to figure out why the queries are not identifying the buckets in windows.

### Checklist

Authors and Reviewer(s), please verify the following:

- [x] A PR description, regardless of the triviality of this change, that communicates the value of this PR
- [x] [Well-formatted conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/) that provide context into the change
- [x] Documentation updated or issue created (provide link to issue/PR)
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] Feature flagged, if applicable

### CODE REVIEW

File: src/homepageExperience/components/steps/cli/ExecuteAggregateQuery.tsx [hunk 1]
```diff
@@ -71,7 +72,11 @@ export const ExecuteAggregateQuery = (props: OwnProps) => {
       />
       <p>In the InfluxDB CLI, run the following:</p>
       <CodeSnippet
-        text={codeSnippet}
+        text={
+          window?.navigator?.userAgent.includes('Windows')
```
Comment (ChitlangeSahas) [inline src/homepageExperience/components/steps/cli/ExecuteAggregateQuery.tsx:76]: should we put this into a utility function? i remember you made a utility to detect ctrl-c keyboard, seems like a good candidate to put in there.

**Review by ChitlangeSahas — APPROVED** [review]
Rest looks great!
