### PR TITLE
fix: Notebook maps error

### LINKED ISSUE #1615: Maps is broken in Notebooks
Trying to run the following query:
```
import "experimental/csv"

csv.from(url: "https:/"+"/raw.githubusercontent.com/russorat/influxdb-data-examples/master/gov/usgs/earthquake/all_week-annotated.csv")
  |> filter(fn: (r) => r._field == "lat" or r._field == "lon")
```

gives me an error in notebooks. Error is on this line: https://github.com/influxdata/ui/blob/master/src/visualization/types/Map/view.tsx#L133

image

### PR DESCRIPTION
**Pull request by zoesteinkamp**
Closes #1615 

Okay so this fixes the color issue by auto assigning the color similar to our logic for the tooltipColumns and this has layer opts be above all code calling for layer properties. I was finding that the code was crashing because it was look for layer.properties.blah and finding nothing. So i moved all the code underneath and i set layerOpts = layers, which was missing so things were still crashing when they checked the properties.

### CODE REVIEW

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 54 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 93 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=master)

File: src/visualization/types/Map/view.tsx [hunk 1]
```diff
@@ -126,16 +124,23 @@ const GeoPlot: FC<Props> = ({result, properties}) => {
         colorField: '_value',
         colors: DEFAULT_THRESHOLDS_GEO_COLORS,
         isClustered: false,
-        tooltipColumns: tooltipColumns,
+        tooltipColumns: [],
```
Comment (Palakp41) [inline src/visualization/types/Map/view.tsx:127]: I think this should be updated to be:
```
tooltipColumns: [],
colors: []
```
because we want to to give them a default value but later we can check if `layerOpts[0].tooltipColumns` is empty, then we can updated to use fluxgroup key union values.

File: src/visualization/types/Map/view.tsx [hunk 2]
```diff
@@ -126,16 +124,23 @@ const GeoPlot: FC<Props> = ({result, properties}) => {
...
       },
     ]
+    properties.layers = layersOpts
```
Comment (Palakp41) [inline src/visualization/types/Map/view.tsx:130]: This seems a bit weird to me. First on Line 118, we are giving `layerOpts` value of `properties.layers` and then doing the opposite here. What if you removed this and instead of using `properties.layers` on line 133, you use `layerOpts`?

File: src/visualization/types/Map/view.tsx [hunk 3]
```diff
@@ -126,16 +124,23 @@ const GeoPlot: FC<Props> = ({result, properties}) => {
...
   }
 
-  layersOpts[0].tooltipColumns = tooltipColumns
+  const tooltipColumns = _.isEmpty(properties.layers[0].tooltipColumns)
```
Comment (Palakp41) [inline src/visualization/types/Map/view.tsx:133]: Can you update this to be: 
```
const tooltipColumns = _.isEmpty(layerOpts[0].tooltipColumns)
```

File: src/visualization/types/Map/view.tsx [hunk 4]
```diff
@@ -126,16 +124,23 @@ const GeoPlot: FC<Props> = ({result, properties}) => {
...
+    ? result.fluxGroupKeyUnion
+    : properties.layers[0].tooltipColumns
 
-  if (!layers[0].colors[0].id) {
-    layersOpts[0].colors = DEFAULT_THRESHOLDS_GEO_COLORS
-  }
+  const colorChoice = _.isEmpty(properties.layers[0].colors)
```
Comment (Palakp41) [inline src/visualization/types/Map/view.tsx:137]: Can you update this to be:
```
const colorChoice = _.isEmpty(layerOpts[0].colors)
```

**Review by Palakp41 — APPROVED** [review]
Looks good!
