### PR TITLE
fix: correct globalheader switch-account URL.

### LINKED ISSUE #5293: fix switch-account URL for globalheader
GlobalHeader 'switch-account' is not currently working as intended. The `switchAccount` function routes the user to orgs/orgId/accounts/accountId, but should be routing the user simply to /accounts/accountId.

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. enable multiOrg and quartzIdentity feature flags.
2. refresh page
3. switch account from globalHeader

**Expected behavior:**
Refresh of app; switch into new account

**Actual behavior:**
`404`, as URL for that account is not visitable

**Visual Proof:**
https://user-images.githubusercontent.com/91283923/182898197-c064a3f9-3a52-41b9-a146-0dc942727292.mov

### PR DESCRIPTION
**Pull request by wdoconnell**
Closes #5293

Switch-account in GlobalHeader was not working because the URL the user needs to visit to change accounts should be `${CLOUD_URL}/accounts/:accountId` (not the current URL that included the org id - like `/orgs/:orgId/accounts/:accountId`. We can be confident this works effectively, since this exact URL is used on the switch account page (which works).   

The switch orgs URL should be similarly updated to `$CLOUD_URL/orgs/:orgId`.

### Checklist

Authors and Reviewer(s), please verify the following:

- [X] A PR description, regardless of the triviality of this change, that communicates the value of this PR
- [X] [Well-formatted conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/) that provide context into the change
- [X] Documentation updated or issue created (provide link to issue/PR)
- [X] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [X] Feature flagged, if applicable - YES, `multiOrg`

### CODE REVIEW

File: src/identity/components/GlobalHeader/AccountDropdown.tsx [hunk 1]
```diff
@@ -1,22 +1,30 @@
+// Libraries
 import React, {FC} from 'react'
 import {IconFont} from '@influxdata/clockface'
-import {OrganizationSummaries, UserAccount} from 'src/client/unityRoutes'
-import {
```
Comment (wdoconnell) [inline src/identity/components/GlobalHeader/AccountDropdown.tsx:4]: This is just a refactor/reorganization of imports.

File: src/identity/components/GlobalHeader/AccountDropdown.tsx [hunk 2]
```diff
@@ -1,22 +1,30 @@
...
 const menuStyle = {width: '250px'}
 
+// Components
+import {
+  GlobalHeaderDropdown,
+  TypeAheadMenuItem,
+} from 'src/identity/components/GlobalHeader/GlobalHeaderDropdown'
+
+// Constants
+import {CLOUD_URL} from 'src/shared/constants'
```
Comment (wdoconnell) [inline src/identity/components/GlobalHeader/AccountDropdown.tsx:26]: CLOUD_URL points to /auth in cloud environments, so the URL for switching account ends up being: /auth/accounts/:accountId. 

Tested this in remocal, verified that it's the same code as is used for switch-account; and verified in prod that this is the URL that is actually hit by the switch-account page.

**Review by TCL735 — APPROVED** [review]

File: src/identity/components/GlobalHeader/OrgDropdown.tsx [hunk 3]
```diff
@@ -1,13 +1,21 @@
...
+
+// Types
+import {OrganizationSummaries} from 'src/client/unityRoutes'
+
+// Constants
+import {CLOUD_URL} from 'src/shared/constants'
 
 const switchOrg = (org: TypeAheadMenuItem) => {
-  window.location.href = `/orgs/${org.id}`
+  window.location.href = `${CLOUD_URL}/orgs/${org.id}`
```
Comment (wdoconnell) [inline src/identity/components/GlobalHeader/OrgDropdown.tsx:18]: I've confirmed both of these URLs with the AIM team.

**Review by TCL735 — APPROVED** [review]
