### PR TITLE
fix(5617): composition styling not in notebooks

### LINKED ISSUE #5617: Schema Composition: the highlight code block is shown up in notebook editor
## About the bug

When the feature flag `schemaComposition` is on, the highlight code block is shown up in notebook editor

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Turn on feature flag `schemaComposition`
2. Go to Notebooks and create a new one
3. Select a bucket, a measurement, and a field
4. Click the `...` button and select "Convert to |> Flux"

**Expected behavior:**
No highlight code block

**Actual behavior:**
A blue highlight code block is shown

**Visual Proof:**

https://user-images.githubusercontent.com/14298407/187792511-499e73ab-7bb6-419b-91da-a6883ed40bb3.mov

### PR DESCRIPTION
**Pull request by wiedld**
Closes #5617 

## Bug:
* the persisted `fluxQueryBuilder` is the user preference, not if the user is currently in the new QxBuilder.
* instead, use the current pattern with which we check it. (This^^ bool, and the route path.)

## Vid:

https://user-images.githubusercontent.com/10232835/188037746-347828a7-2b40-4d1a-956e-e552727321c7.mov

### CODE REVIEW

File: src/shared/components/FluxMonacoEditor.tsx [hunk 1]
```diff
@@ -130,36 +134,41 @@ const FluxEditorMonaco: FC<Props> = ({
...
-            automaticLayout: true,
-            readOnly: readOnly || false,
-            wordWrap: wrapLines ?? 'off',
-            scrollBeyondLastLine: false,
-          }}
-          editorDidMount={editorDidMount}
-        />
-        <div id={ICON_SYNC_ID} className="sync-bar">
-          <Icon glyph={IconFont.Sync} className="sync-icon" />
+  return useMemo(
```
Comment (wiedld) [inline src/shared/components/FluxMonacoEditor.tsx:137]: Added use `useMemo()` because the tests were failing otherwise.

Review the last commit, before and after the change. We had the browser re-rendering for 1 extra cycle per keydown (key typed) in the editor. This meant that in the tests with the super fast typing, it did not always correctly perform the recognition of the cypress-typed closing paran (versus the auto-complete paran provided earluer). Therefore we were failing with extra closing brackets/parans.

Example failures (from CI test artifacts):
Screen Shot 2022-09-06 at 3 08 52 PM
Screen Shot 2022-09-06 at 3 07 45 PM

File: src/shared/components/FluxMonacoEditor.tsx [hunk 2]
```diff
@@ -130,36 +134,41 @@ const FluxEditorMonaco: FC<Props> = ({
...
+              },
+              overviewRulerBorder: false,
+              automaticLayout: true,
+              readOnly: readOnly || false,
+              wordWrap: wrapLines ?? 'off',
+              scrollBeyondLastLine: false,
+            }}
+            editorDidMount={editorDidMount}
+          />
+          {isNewQxBuilder && (
```
Comment (wiedld) [inline src/shared/components/FluxMonacoEditor.tsx:163]: The use of `isNewQxBuilder` conditional render is the only change here, outside of the useMemo.

File: src/shared/components/FluxMonacoEditor.tsx (hunk 1 above)
Comment (appletreeisyellow) [reply src/shared/components/FluxMonacoEditor.tsx:137]: Good to know!

**Review by appletreeisyellow — APPROVED** [review]
Thanks for fixing this!
