### PR TITLE
fix: code samples for client libraries in OSS show correctly

### LINKED ISSUE #1194: Client libraries markdown code examples incorrect for OSS
When running the UI with OSS, the client libraries details view page for a client library does not show correctly. The code sample does not replace the token/bucket/org in the code examples either initially, or when changing a selection, see example screenshot below when viewing the page for the Go client library:

image

The UI needs to be updated so that the code examples show the appropriate token/bucket/org for OSS.

### PR DESCRIPTION
**Pull request by wbaker85**
Closes #1194

Updated the `ReactMarkdown` component to pass the prop `renderers` along in the not-cloud case so that the placeholders in the code previews get interpolated with the actual values.

### CODE REVIEW

**Comment by hercules-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 59 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 93 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?vars%5Blighthouse_score_branch%5D=1195)

File: src/shared/components/views/MarkdownRenderer.tsx [hunk 1]
```diff
@@ -67,6 +67,11 @@ export const MarkdownRenderer: FC<Props> = ({
 
   // load images locally to your heart's content. caveat emptor
   return (
-    <ReactMarkdown source={text} className={className} escapeHtml={false} />
+    <ReactMarkdown
+      source={text}
+      className={className}
+      renderers={{...cloudRenderers}}
```
Comment (Asalem1) [inline src/shared/components/views/MarkdownRenderer.tsx:73]:
```suggestion
      renderers={cloudRenderers}
```

**Review by Asalem1 — APPROVED** [review]
Not sure if spreading a new object is necessary, that recommended change should suffice. If you tried it out prior to this PR and it didn't work for some reason feel free to ignore the suggestion

File: src/shared/components/views/MarkdownRenderer.tsx (hunk 1 above)
Comment (wbaker85) [reply src/shared/components/views/MarkdownRenderer.tsx]: Thanks for the suggestion! I tried this out and it works fine. The component doesn't ever get more than one "renderer" in OSS mode.
