### PR TITLE
fix: maps in notebooks

### LINKED ISSUE #866: Error States when Map is not rendered
Currently, we have two error states when map is not rendered:
1. When Map service is down or returns an error we display:
    > Map type is having issues connecting to the server. Please try again later.'
2. When data provided is not supported by Maps, for ex: not given lat or lon, we display:
      >  Map type is not supported with the data provided: Missing latitude/longitude values

@kristinarobinson Is this wording right to display in these cases? if not, who do we reach out to get proper decision.

### PR DESCRIPTION
**Pull request by Palakp41**
Closes #866 #1228

When viewing maps for visualization on Notebooks/Flows, the maps weren't rendering because the properties we were sending to giraffe are the defaults (with empty layers) and not the ones we use in Data explorer.

### CODE REVIEW

File: src/visualization/types/Map/view.tsx [hunk 1]
```diff
@@ -109,6 +109,28 @@ const GeoPlot: FC<Props> = ({result, properties}) => {
     bingKey: '',
   }
 
+  let layersOpts = layers
```
Comment (hoorayimhelping) [inline src/visualization/types/Map/view.tsx:112]:
```suggestion
  let layersOpts = [...layers]
```

this will create a copy for you. the way it is now will create a reference, and changing `layerOpts` will change `layers`.

not a big deal thought since `layers` doesn't get used here, but good practice.

**Review by hoorayimhelping — APPROVED** [review]
This looks good as a fix, but do you have any idea of how to fix this up longer term? I imagine this is a problem with other visualization types as well

**Comment by Palakp41** [comment]
> This looks good as a fix, but do you have any idea of how to fix this up longer term? I imagine this is a problem with other visualization types as well

I don't see any other visualization types having issues. I think we will probably need to remove this in the next epic when we use customize options for layers and color codes.

File: src/visualization/types/Map/view.tsx (hunk 1 above)
Comment (Palakp41) [reply src/visualization/types/Map/view.tsx:112]: yeah makes sense. good idea.

**Comment by Palakp41** [comment]
alchemy please merge

**Comment by Palakp41** [comment]
alchemy please merge
