### PR TITLE
fix: remove that variable nonsense

### LINKED ISSUE #162: Metric selector kills previous results
while scoping out influxdata/idpe#8802, turns out that the metric selector has created a condition where we can't use previous results. stems from the aggregate window being applied.

### PR DESCRIPTION
**Pull request by drdelambre**
Kapture 2020-10-28 at 17 30 03

closes #162 
closes influxdata/idpe#8802

### CODE REVIEW

File: src/flows/pipes/Data/index.ts [hunk 1]
```diff
@@ -51,7 +51,7 @@ export default register => {
       }
 
       if (aggregateFunction?.name) {
-        text += `  |> aggregateWindow(every: v.windowPeriod, fn: ${aggregateFunction.name}, createEmpty: false)|> yield(name: "${aggregateFunction.name}")`
```
Comment (Asalem1) [inline src/flows/pipes/Data/index.ts:54]: i think we need a space prepended for formatting when we preview the text

**Review by Asalem1 — APPROVED** [review]
a small thing, might wanna see how this looks when we export it as a task
