### PR TITLE
fix: accordion header toggles when individual resources are empty

### LINKED ISSUE #2446: Tokens: Header toggles have issue when no individual resources
When there are no telegraf configs to display, the header toggles don't work upon selecting all.
Add design to show `read` and `write` tooltips on top of the toggles.

### PR DESCRIPTION
**Pull request by Palakp41**
Closes #2446 

This pr fixes the issues surrounding the accordion and the header toggles. Also, have added some styling changes around the accordion

### CODE REVIEW

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 60 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=2464)

File: src/authorizations/components/redesigned/CustomApiTokenOverlay.tsx [hunk 1]
```diff
@@ -52,9 +54,45 @@ export const CustomApiTokenOverlay: FC<OwnProps> = props => {
...
+                style={{textAlign: 'start', margin: '5px 0px'}}
+              >
+                <FlexBox.Child basis={40} grow={8}>
+                  <InputLabel size={ComponentSize.ExtraSmall}>
+                    Resources
+                  </InputLabel>
+                </FlexBox.Child>
+                <FlexBox.Child
+                  grow={1}
+                  style={{alignItems: 'left', marginLeft: '20px'}}
```
Comment (hoorayimhelping) [inline src/authorizations/components/redesigned/CustomApiTokenOverlay.tsx:73]: should this be a css class in a css file?

File: src/authorizations/components/redesigned/ResourceAccordion.tsx [hunk 2]
```diff
@@ -71,34 +73,47 @@ class ResourceAccordion extends Component<Props, State> {
...
-              />
-            ) : (
-              <ResourceAccordionBody
-                resourceName={resource}
-                permissions={permissions[resource]}
-                onToggle={this.handleIndividualToggle}
-                title="Individual Bucket Names"
-              />
-            )}
+            {isEmpty(permissions[resource].sublevelPermissions)
```
Comment (hoorayimhelping) [inline src/authorizations/components/redesigned/ResourceAccordion.tsx:76]: alternatively, this might be a little clearer if it were written like this:

```ts
{!isEmpty(permissions[resource].sublevelPermissions) &&
  this.getAccordionBody(resourceName, resource)}
```

but your call

File: src/authorizations/components/redesigned/ResourceAccordionHeader.tsx [hunk 3]
```diff
@@ -65,35 +41,42 @@ export const ResourceAccordionHeader: FC<OwnProps> = props => {
...
       >
         <FlexBox.Child basis={40} grow={8}>
           <InputLabel size={ComponentSize.Medium}>{title}</InputLabel>
         </FlexBox.Child>
-        <FlexBox.Child grow={1}>
+        <FlexBox.Child
+          grow={1}
+          onClick={(e: any) => {
+            e.stopPropagation()
+          }}
```
Comment (hoorayimhelping) [inline src/authorizations/components/redesigned/ResourceAccordionHeader.tsx:52]: since this is used in three places, why not make a single function that does this that doesn't have to be created on every render loop - right now this same function gets created 3x per render, but it only really needs to be created once.

Also, can you call it `event` or `evt` instead of `e` please? 😁

**Review by hoorayimhelping — APPROVED** [review]
LGTM, some minor style comments

**Review by hoorayimhelping — APPROVED** [review]
