### PR TITLE
fix: redirect to Quartz login upon session expiration

### LINKED ISSUE #4657: Redirect to main login page after UI session expiry
The UI hits the /me endpoint every minute. When the session expires, the UI gets an unauthorized response from /me and then it decides what to do. Right now it redirects to the cluster login page (which is deprecated). The UI needs to redirect to the quartz login page. 

https://<cloud2.influxdata.com>/login (where <cloud2.influxdata.com> is the appropriate Quartz URL from which the UI is served: prod/staging/remocal/local). 

See EAR https://github.com/influxdata/EAR/issues/3012

### PR DESCRIPTION
**Pull request by TCL735**
Closes #4657 

When a session expires, redirect to the Quartz login page rather than the cluster's login page.

### CODE REVIEW

**Comment by TCL735** [comment]
@asalem1 does this look right to you? I'm taking a stab here and may be totally off base.

File: src/Signin.tsx [hunk 1]
```diff
@@ -117,9 +113,7 @@ export class Signin extends PureComponent<Props, State> {
        * Quartz is integrated into that environment
        */
       if (CLOUD && isFlagEnabled('authSessionCookieOn')) {
-        const url = new URL(
-          `${window.location.origin}${CLOUD_LOGIN_PATHNAME}?redirectTo=${window.location.href}`
-        )
+        const url = new URL(`${CLOUD_URL}?redirectTo=${window.location.href}`)
```
Comment (asalem1) [inline src/Signin.tsx:116]: 🤷🏽 this should work w/r/t to directing the user the Quartz login page, but I don't think the `redirectTo` stuff will be relevant. Since we're dealing with authentication and signing in, I would feature flag this behind a public feature flag so that we ensure that there's some sort of stability in place prior to merging in something that may unintentionally break auth

**Review by asalem1 — CHANGES_REQUESTED** [review]

**Comment by TCL735** [comment]
Changes pending. We will turn this into a page refresh rather than redirect. By refreshing the page, Quartz will automatically handle everything: from detecting an unauthenticated user to login page to redirect back to previous page user was on.

File: src/Signin.tsx [hunk 2]
```diff
@@ -112,20 +112,26 @@ export class Signin extends PureComponent<Props, State> {
...
       if (CLOUD) {
+        if (isFlagEnabled('useQuartzLogin')) {
+          window.location.reload()
+          throw error
+        }
+
+        /**
+         * We'll need this authSessionCookieOn flag off for tools until
+         * Quartz is integrated into that environment
+         */
```
Comment (hoorayimhelping) [inline src/Signin.tsx:125]: i think we can remove this comment since it's not relevant anymore

File: src/Signin.tsx [hunk 3]
```diff
@@ -112,20 +112,26 @@ export class Signin extends PureComponent<Props, State> {
...
-        )
-        setToLocalStorage('redirectTo', window.location.href)
-        window.location.href = url.href
-        throw error
-      }
 
       if (CLOUD) {
+        if (isFlagEnabled('useQuartzLogin')) {
+          window.location.reload()
+          throw error
```
Comment (hoorayimhelping) [inline src/Signin.tsx:119]: like we discussed offline, I think we should remove this line since it won't really do anything and it tends to communicate that is doing something

File: src/Signin.tsx [hunk 4]
```diff
@@ -112,20 +112,26 @@ export class Signin extends PureComponent<Props, State> {
...
+         * We'll need this authSessionCookieOn flag off for tools until
+         * Quartz is integrated into that environment
+         */
+        if (isFlagEnabled('authSessionCookieOn')) {
+          const url = new URL(
+            `${window.location.origin}${CLOUD_LOGIN_PATHNAME}?redirectTo=${window.location.href}`
+          )
+          setToLocalStorage('redirectTo', window.location.href)
+          window.location.href = url.href
+          throw error
```
Comment (hoorayimhelping) [inline src/Signin.tsx:132]: same here with this line

**Review by hoorayimhelping — COMMENTED** [review]
couple of comments about removing unneeded lines
