### PR TITLE
fix: show search bar for bucket even when no bucket is found

### LINKED ISSUE #5072: In New Data Explorer, Bucket Search is lost when searching for a non-existent bucket
## About the bug

**Steps to reproduce:**

1. Launch new Data Explorer
2. Select the bucket field
3. Type the name of a bucket that doesn't exist into the search box

**Expected behavior:**
In this scenario, not finding a bucket is expected, but I would still expect to be able to alter my search to try to find a different bucket.

**Actual behavior:**
The message "No Buckets Available" is shown and there is no ability to re-show the bucket list or search for a different bucket.  The schema browser is basically broken in this scenario.  Easy to re-produce.

**Visual Proof:**

Screen Shot 2022-07-15 at 12 04 57 PM

Note. Reported by @saraghds ; very easy to reproduce.

### PR DESCRIPTION
**Pull request by appletreeisyellow**
Closes #5072 

This PR fixes the bug that search bar disappears when there is no found buckets.
 
## Before

image

## After

Screen Shot 2022-07-18 at 11 00 16 AM

### Checklist

Authors and Reviewer(s), please verify the following:

- [x] A PR description, regardless of the triviality of this change, that communicates the value of this PR
- [x] [Well-formatted conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/) that provide context into the change
- [x] Documentation updated or issue created (provide link to issue/PR)
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] Feature flagged, if applicable

### CODE REVIEW

File: src/shared/components/SearchableDropdown.tsx [hunk 1]
```diff
@@ -54,7 +54,7 @@ const SearchableDropdown: FC<Props> = ({
   )
 
   let body: JSX.Element | JSX.Element[] = (
-    <div className="searchable-dropdown--empty">{emptyText}</div>
+    <Dropdown.ItemEmpty>{emptyText}</Dropdown.ItemEmpty>
```
Comment (appletreeisyellow) [inline src/shared/components/SearchableDropdown.tsx:57]: Replacing the customized css with clockface component to keep the UI consistant

**Review by drdelambre — APPROVED** [review]
