### PR TITLE
fix: Settings page style issues fix clockface 3.0

### LINKED ISSUE #2562: Settings Page style issues
Clockface integration has caused some styling issues and this issue focuses on the settings page. 
* Variables Tab
* Templates Tab
* Labels Tab

### PR DESCRIPTION
**Pull request by ChitlangeSahas**
Closes #2562 

Fixes the styling issues caused by the import of clockface 3. Also fixes a couple e2e tests.

### CODE REVIEW

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 57 | :red_circle:
accessibility | 97 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=2574)

**Review by daviddkkim — APPROVED** [review]
lgtm

File: src/variables/components/UpdateVariableOverlay.tsx [hunk 1]
```diff
@@ -129,30 +129,31 @@ class UpdateVariableOverlay extends PureComponent<Props, State> {
...
+                type={ButtonType.Submit}
+                color={ComponentColor.Primary}
+                status={
+                  hasValidArgs
+                    ? ComponentStatus.Default
+                    : ComponentStatus.Disabled
+                }
+                onClick={e => {
+                  this.handleSubmit(e)
+                  onClose()
```
Comment (hoorayimhelping) [inline src/variables/components/UpdateVariableOverlay.tsx:152]: let's pull this out into a function that isn't re-created on render. This will cause re-renders since an anonymous function is being re-created on every render, which will be a different prop for `Button` on ever render.

File: src/variables/components/VariableContextMenu.tsx [hunk 2]
```diff
@@ -19,29 +29,55 @@ export default class VariableContextMenu extends PureComponent<Props> {
...
-      </Context>
+      <FlexBox margin={ComponentSize.ExtraSmall}>
+        <ConfirmationButton
+          color={ComponentColor.Colorless}
+          icon={IconFont.Trash_New}
+          shape={ButtonShape.Square}
+          size={ComponentSize.ExtraSmall}
+          confirmationLabel="Yes, Delete this Variable"
+          onConfirm={() => {
+            onDelete(variable)
```
Comment (hoorayimhelping) [inline src/variables/components/VariableContextMenu.tsx:42]: same thing here - pull this function out into a function that isn't created on render. since it only accesses props, it doesn't need to be re-made every render cycle

File: src/variables/components/VariableContextMenu.tsx [hunk 3]
```diff
@@ -19,29 +29,55 @@ export default class VariableContextMenu extends PureComponent<Props> {
...
+              <List.Item
+                onClick={onRename}
+                size={ComponentSize.Small}
+                style={{fontWeight: 500}}
+                testID="context-rename-variable"
+              >
+                Rename
+              </List.Item>
+            </List>
+          )}
```
Comment (hoorayimhelping) [inline src/variables/components/VariableContextMenu.tsx:77]: same here, let's make this an instance method on the class

**Review by hoorayimhelping — APPROVED** [review]
LGTM, but some some comments about not re-creating anonymous functions for event handlers on ever render loop (since that causes re-renders and i'm knee-deep in re-renderland)

File: src/variables/components/UpdateVariableOverlay.tsx (hunk 1 above)
Comment (ChitlangeSahas) [reply src/variables/components/UpdateVariableOverlay.tsx:152]: We will have to leave this one because of how the react context works, the `onClose` is not accessible outside of the arrow function. The other two instances of where re-renders could be avoided, have been fixed 👍
