### PR TITLE
fix: make DatePicker and TimeRangeDropdown respect the user timezone setting

### LINKED ISSUE #1827: Bug: Dashboard "Custom Time Range" picker does not show correct times.
# Summary

The custom time range picker does not respect the the local/utc timezone toggle button. The picker always loads with a timestamp that appears to be UTC e.g. `2021-06-28T16:04:52.486Z`. If `Local` time is selected, it should show times in the local timezone (e.g. +7). If `UTC`, then utc. 

Worse, when `UTC` is selected for the dashboard, the picker is actually showing _local_ times with simply a `Z`. See the attached gif. The dashboard is set to utc, when I pick times in the modal e.g. `18:00`, the displayed time says `2021-06-24T01:00:00.185Z` instead of the correct `2021-06-23T18:00:00.185Z`, which you can see once I close the picker modal and look at the displayed time range.

time picker

**Steps to reproduce:**
1. Create a dashboard with at least one cell with a valid, data returning query.
2. Change the dashboard time from `Local` to `UTC`.
3. Pick a custom time range and note how selecting a UTC date and time does not match the displayed time in the modal, but the correct time range is displayed after clicking `Apply Time Range`

**Expected behavior:**
Dates and times displayed should show the correct time _in the selected timezone_.

**Actual behavior:**
See above: datetimes are incorrect.

**Environment info:**
influx cloud2

### PR DESCRIPTION
**Pull request by ChitlangeSahas**
Closes #1827

This PR addresses two components and makes them respect the App's global timezone settings:

* The `TimeRangeDropdown`: This component needed the timezone information so it could display the time in the correct zone, thus respecting the user preference.
* The `DatePicker`: that was based on `react-datepicker` needed some tweaks, the underlying library has a known [issue](https://github.com/Hacker0x01/react-datepicker/issues/498) of forcing the `Local` timezone. 

A brief of the solution:

When the User selects `UTC` in the dropdown the `DatePicker` converts that UTC into `Local time`. We need to display the UTC time in the `DatePicker`, so I added the `UTC time offset` to the `Local` time, and hence it displays the desired UTC time.  

The date picker works fine with `Local` time zone settings, no changes were necessary for that. 

Video: 

https://user-images.githubusercontent.com/18511823/125701148-59daf02d-3a9d-4838-9e2d-4e3482dfd9fd.mov

Screenshot, just in case.

Screen Shot 2021-08-02 at 2 52 59 PM

### CODE REVIEW

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 60 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=2155)

**Comment by genehynson** [comment]
fyi you can make this PR a "draft PR" so others know not to review / merge it
Screen Shot 2021-07-27 at 1 54 53 PM

**Comment by ChitlangeSahas** [comment]
> fyi you can make this PR a "draft PR" so others know not to review / merge it
> Screen Shot 2021-07-27 at 1 54 53 PM

@genehynson Thank you gene! i'll do that!

File: src/shared/utils/duration.ts [hunk 1]
```diff
@@ -166,14 +171,12 @@ export const getTimeRangeLabel = (
     return timeRange.lower
   }
   if (timeRange.type === 'custom') {
-    const lower = moment(timeRange.lower).format(TIME_RANGE_FORMAT)
-    const upper = moment(timeRange.upper).format(TIME_RANGE_FORMAT)
-    if (singleDirection && singleDirection === TimeRangeDirection.Upper) {
+    const formatter = createDateTimeFormatter(TIME_RANGE_FORMAT, timeZone)
+    const lower = formatter.format(new Date(timeRange.lower))
+    const upper = formatter.format(new Date(timeRange.upper))
+    if (singleDirection === TimeRangeDirection.Upper) {
```
Comment (hoorayimhelping) [inline src/shared/utils/duration.ts:177]: nice, cleaning up an unnecessary case in this `if` statement :+1:

File: src/shared/components/dateRangePicker/DatePicker.tsx [hunk 2]
```diff
@@ -115,10 +129,12 @@ export default class DatePicker extends PureComponent<Props, State> {
     }
 
     if (inputFormat) {
-      return moment(dateTime).format(inputFormat)
+      const formatter = createDateTimeFormatter(inputFormat, timeZone)
+      return formatter.format(new Date(dateTime))
     }
+    const formatter = createDateTimeFormatter('YYYY-MM-DD HH:mm:ss', timeZone)
```
Comment (hoorayimhelping) [inline src/shared/components/dateRangePicker/DatePicker.tsx:135]: minor nit: let's refer to `DEFAULT_TIME_FORMAT` rather than the string `'YYYY-MM-DD HH:mm:ss'`

**Review by hoorayimhelping — APPROVED** [review]
good work!

had a minor nit about using the `DEFAULT_TIME_FORMAT` constant instead of the string directly

hold onto your butts!
[](https://www.youtube.com/watch?v=-W6as8oVcuM)

File: src/shared/components/dateRangePicker/DatePicker.tsx (hunk 2 above)
Comment (ChitlangeSahas) [reply src/shared/components/dateRangePicker/DatePicker.tsx:135]: True, will do that refactor!
