### PR TITLE
fix: dont show header on 404 page

### LINKED ISSUE #5750: Multi Org Phase 1 - When a page returns 404, we should not show the global header
If a page does not exist and we redirect to 404 page, we shouldn't show the global header.

Image

### PR DESCRIPTION
**Pull request by wdoconnell**
Closes #5750 

In cloud, the multi-org global header displayed on 404 pages, because it was rendered by the parent of the component containing our React Router routes (SetOrg).

This PR adds another condition for rendering the header: it won't display if the current page is the `not found` page. 

Conveniently, we already have a redux state for this (which is used in dashboards). So detecting the 'not found' page simply requires updating (and cleaning up) that state when the user hits the `Not Found` component.

Before
--

https://user-images.githubusercontent.com/91283923/194159129-70806657-b8d7-410f-8601-446805c046d2.mov

After
--

https://user-images.githubusercontent.com/91283923/194159141-8626a047-8675-4ac2-870e-2758438ba804.mov

### Checklist

Authors and Reviewer(s), please verify the following:

- [X] A PR description, regardless of the triviality of this change, that communicates the value of this PR
- [X] [Well-formatted conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/) that provide context into the change
- [X] Documentation updated or issue created (provide link to issue/PR)
- [X] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [X] Feature flagged, if applicable - NO

### CODE REVIEW

File: src/shared/components/NotFound.tsx [hunk 1]
```diff
@@ -169,6 +174,13 @@ const NotFound: FC = () => {
     }
   }, [handleDeepLink])
 
+  useEffect(() => {
+    dispatch(setCurrentPage('not found'))
+    return () => {
+      dispatch(setCurrentPage('not set'))
```
Comment (blegesse-git) [inline src/shared/components/NotFound.tsx:180]: just to clarify, is this return statement here to set the `currentPage` state to `not set` right after the component unmounts?

**Review by blegesse-git — APPROVED** [review]

File: src/shared/components/NotFound.tsx (hunk 1 above)
Comment (wdoconnell) [reply src/shared/components/NotFound.tsx:180]: Yup! You nailed it @blegesse-git 

This is also the way we currently handle it on the dashboards page.

Comment (wdoconnell) [reply src/shared/components/NotFound.tsx:180]: Basically - this ensures we get a redux state update whenever the user clicks away from the "Not Found" page - whether it's through navigating to a new url, clicking a link on the navbar, etc.

Comment (blegesse-git) [reply src/shared/components/NotFound.tsx:180]: thanks for the explanation! makes perfect sense

**Comment by TCL735** [comment]
what about the side nav? it's funny that we still have a side nav. But i guess the side nav is helpful in navigating away from the 404 page.

**Review by TCL735 — APPROVED** [review]

**Comment by wdoconnell** [comment]
> what about the side nav? it's funny that we still have a side nav. But i guess the side nav is helpful in navigating away from the 404 page.

Yeah this is existing behavior @TCL735 , which is interesting. Here's how it works (this PR doesn't change it):

If you try to navigate to a URL that does include your org route - /orgs/39024902/BLAH, it will still show the left nav.

If you try to navigate to a URL that doesn't include your org route /BLAH, it won't show the left nav.
