### PR TITLE
fix: fix mailgun alert

### LINKED ISSUE #3805: Notebooks(Alert): Mailgun Test Alert fails with empty flux query
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. In MailGun setup an account and then an Email API integration using the Web API and Curl.  Copy and save the API Key and domain for later use in Influxdb UI.  
2. Go to Influxdbv2 UI (note that during this test the feature flag 'notebooksNewEndpoints' was set)
3. Add test data to a bucket
4. Create an Alert Notebook
5. Use the test data to define the query
6. In the alert section choose MailGun
7. Add the key and domain from the first step to the configuration
8. Use the MailGun account email for the _from_ field, and in the _to_ field add an email address to which you have access
9. Click  "Test Alert" 

**Expected behavior:**

Expected for the Test Alert to be sent

**Actual behavior:**

Received an Error Notification "Failed to send the test alert to mailgun.  Please try again".
In developer tools > network upon inspecting the call to `/query?` it appears the request payload query is an empty string. 

**Visual Proof:**

NBMailGunFail01

## About your environment

**Environment info:**
Testing in K8SIDPE Remocal.

Latest commit in project UI:

```
commit 65592aad01b9ddd369107e63c22227b075b9dd23 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Author: Chitlange Sahas <chitlangesahas@gmail.com>
Date:   Fri Feb 4 10:58:12 2022 -0700
```

Latest commit in K8SIDPE
```
commit 67f3b9f7d21b0782bd36ec0f268cfb9df815bc89 (HEAD -> master, origin/master, origin/alchemy/automatic, origin/HEAD)
Author: Hercules Mango Churchill <alchemy@influxdata.com>
Date:   Tue Feb 8 02:20:47 2022 +0000

```

**Logs:**

```
 POST https://twodotoh-dev-bonitoo-kk.remocal.influxdev.co/api/v2/query?orgID=4b6f15c507695930 400
basic	@	query.tsx:324
query	@	query.tsx:397
query	@	flow.query.tsx:156
handleTestEndpoint	@	view.tsx:337
callCallback	@	react-dom.development.js:3945
fn.___hb	@	honeybadger.js:495
invokeGuardedCallbackDev	@	react-dom.development.js:3994
invokeGuardedCallback	@	react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError	@	react-dom.development.js:4070
executeDispatch	@	react-dom.development.js:8243
processDispatchQueueItemsInOrder	@	react-dom.development.js:8275
processDispatchQueue	@	react-dom.development.js:8288
dispatchEventsForPlugins	@	react-dom.development.js:8299
(anonymous)	@	react-dom.development.js:8508
batchedEventUpdates$1	@	react-dom.development.js:22396
batchedEventUpdates	@	react-dom.development.js:3745
dispatchEventForPluginEventSystem	@	react-dom.development.js:8507
attemptToDispatchEvent	@	react-dom.development.js:6005
dispatchEvent	@	react-dom.development.js:5924
unstable_runWithPriority	@	scheduler.development.js:468
runWithPriority$1	@	react-dom.development.js:11276
discreteUpdates$1	@	react-dom.development.js:22413
discreteUpdates	@	react-dom.development.js:3756
dispatchDiscreteEvent	@	react-dom.development.js:5889
fn.___hb	@	honeybadger.js:495
```

### PR DESCRIPTION
**Pull request by subirjolly**
Closes #3805 

**Error**
image

There were a couple of underlying causes. The first cause was with the existing escape sequence. The second cause was that the http post was not conforming to what mailgun expects.
Updated to send the payload expected by mailgun. Because we aren't escaping much, there's no issue of escape sequence anymore.

### CODE REVIEW

File: src/flows/pipes/Notification/endpoints/Mailgun/index.ts [hunk 1]
```diff
@@ -33,37 +35,56 @@ export default register => {
...
-  )`,
-    generateTestQuery: data => `
-    apiKey = secrets.get(key: "{data.apiKey}")
-    http.post(
-        url: "https://api.mailgun.net/v3/${data.domain}/messages",
+      apiKey = secrets.get(key: "${data.apiKey}")
+      auth = http.basicAuth(u: "api", p: "\${apiKey}")
+      url = "https://api.mailgun.net/v3/${data.domain}/messages"
+      data = strings.joinStr(arr: [
+          "from=Username mailgun@${data.domain}",
```
Comment (appletreeisyellow) [inline src/flows/pipes/Notification/endpoints/Mailgun/index.ts:42]: Should the `Username` or `Username mailgun` be a variable instead of hard coded string? Looks like anything after `from=` should be an email address

File: src/flows/pipes/Notification/endpoints/Mailgun/index.ts [hunk 2]
```diff
@@ -33,37 +35,56 @@ export default register => {
...
+    },
+    generateTestQuery: data => {
+      const subject = encodeURIComponent('InfluxDB Alert')
+      const message = encodeURIComponent(TEST_NOTIFICATION)
+
+      return `apiKey = secrets.get(key: "${data.apiKey}")
+auth = http.basicAuth(u: "api", p: "\${apiKey}")
+url = "https://api.mailgun.net/v3/${data.domain}/messages"
+data = strings.joinStr(arr: [
+  "from=Username mailgun@${data.domain}",
```
Comment (appletreeisyellow) [inline src/flows/pipes/Notification/endpoints/Mailgun/index.ts:69]: Same comment as above

File: src/flows/pipes/Notification/endpoints/Mailgun/index.ts (hunk 1 above)
Comment (subirjolly) [reply src/flows/pipes/Notification/endpoints/Mailgun/index.ts:42]: this is a valid point. I will make a change. Infact, I think we need to change the name of sender from `Username` to `InfluxDB Mailgun`..

@drdelambre Thoughts?

Comment (appletreeisyellow) [reply src/flows/pipes/Notification/endpoints/Mailgun/index.ts:42]: Nice! This makes more sense

Comment (drdelambre) [reply src/flows/pipes/Notification/endpoints/Mailgun/index.ts]: @subirjolly i have no idea how mailgun works. pop up the mailgun docs and see if the username is configurable

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 53 | :red_circle:
accessibility | 97 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=3879)

File: src/flows/pipes/Notification/endpoints/Mailgun/index.ts (hunk 1 above)
Comment (subirjolly) [reply src/flows/pipes/Notification/endpoints/Mailgun/index.ts]: updated to just be email

File: src/flows/pipes/Notification/endpoints/Mailgun/index.ts [hunk 3]
```diff
@@ -33,37 +37,57 @@ export default register => {
...
-    http.post(
-        url: "https://api.mailgun.net/v3/${data.domain}/messages",
+      apiKey = secrets.get(key: "${data.apiKey}")
+      auth = http.basicAuth(u: "api", p: "\${apiKey}")
+      url = "https://api.mailgun.net/v3/${data.domain}/messages"
+      data = strings.joinStr(arr: [
+          "from=${fromEmail}",
+          "to=${data.email}",
+          "subject=${subject}",
+          "text=\${r._message}"
```
Comment (appletreeisyellow) [inline src/flows/pipes/Notification/endpoints/Mailgun/index.ts:47]: Seems like we want to pass `r._message` as a variable. If so, do we want to remove the `\` before the dollor sign? Maybe I'm wrong since I'm not familiar with the syntax here

File: src/flows/pipes/Notification/endpoints/Mailgun/index.ts [hunk 4]
```diff
@@ -33,37 +37,57 @@ export default register => {
...
+        ], v: "&"
+      )
+      http.post(
+        url: url,
         headers: {
-          "Content-type": "application/json",
-          "Authorization": "Basic api:\${apiKey}"
+          "Content-Type": "application/x-www-form-urlencoded",
+          "Authorization": "\${auth}"
```
Comment (appletreeisyellow) [inline src/flows/pipes/Notification/endpoints/Mailgun/index.ts:54]:
```suggestion
          "Authorization": auth
```
Same question as above. I'm not sure about the syntax that if `\` will make the variable to be hard coded string here.

File: src/flows/pipes/Notification/endpoints/Mailgun/index.ts (hunk 3 above)
Comment (wiedld) [reply src/flows/pipes/Notification/endpoints/Mailgun/index.ts:47]: The r is a flux variable, being used for flux string templating.
Which happens to use the same syntax as javascript string templating, so the escaping is to keep it present for flux.

File: src/flows/pipes/Notification/endpoints/Mailgun/index.ts (hunk 4 above)
Comment (subirjolly) [reply src/flows/pipes/Notification/endpoints/Mailgun/index.ts:54]: I am okay with keeping it like this or changing both. As it was like this from the beginning, that suggests that we actually want it to be as is.
