### PR TITLE
fix: not showing error before user input anything

### LINKED ISSUE #3102: Notebooks: Updates to task panel required field flow
Currently, users see an error state showing that Every is required within the Task panel, even before they have a chance to add an Every input. It's confusing to show an error prior to a user submitting inputs and might make them think they've either done something wrong or it's a bug. To fix this, we would like to update the Task panel to show Required and Optional fields, disable Export as Task button prior to required input, and show error state after clicking Export as Task without required input.

AS a user
WHEN I see the subheadings "Required" and "Optional" 
THEN I know which inputs are required to create a task

AS a user
WHEN I haven't filled out the required input on the Task panel
THEN the Export as Task button is disabled

AS a user
WHEN I click the disabled Export as Task button before filling out the required input
THEN I get an error message around the required field

Current Design:

New Design: https://www.figma.com/proto/a7qLfWdlUDrhab9aWIxE65/Notebook-Alerts-and-Tasks?node-id=1189%3A12925&scaling=min-zoom&page-id=1134%3A12703&starting-point-node-id=1189%3A12925

### PR DESCRIPTION
**Pull request by appletreeisyellow**
Closes #3102

Removed the error message for "Required" before users input anything.

Current view:
Screen Shot 2021-12-03 at 10 46 39 AM

### CODE REVIEW

File: src/flows/pipes/Schedule/view.tsx [hunk 1]
```diff
@@ -143,11 +143,11 @@ const Schedule: FC<PipeProp> = ({Context}) => {
   let intervalError = ''
   let offsetError = ''
 
-  if (!data.interval) {
+  if (data?.interval === '') {
```
Comment (drdelambre) [inline src/flows/pipes/Schedule/view.tsx:146]: are these different?

Comment (asalem1) [reply src/flows/pipes/Schedule/view.tsx:146]: They are. The previous implementation had an undefined value so it was automatically registering an error when the user created a task but didn't yet input a change

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 58 | :red_circle:
accessibility | 97 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=3371)

**Review by asalem1 — APPROVED** [review]

**Review by drdelambre — APPROVED** [review]
