### PR TITLE
fix(flows-ui-pagination): fixed the UI pagination for flows and feature flagged it

### LINKED ISSUE #201: Metric Selector Raw Data Table isn't working
### Problem

Not entirely sure what's happening here but it could be related to the changes made in the following PR:

https://github.com/influxdata/ui/pull/168/files

Here's how the bug looks:

### Steps to Reproduce

1. Create a flow with a metric selector
2. Generate & run a query with the metric selector
3. Try and navigate the paginated raw data results

### Expected Behavior

The results of the metric selector should be paginated, and the number of rows that are being paginated through should not be updated with every click of the next button

### PR DESCRIPTION
**Pull request by Asalem1**
Closes #201 

### Problem

The way that the RawDataTable is currently built out, the view layer can't parse partial CSVs and just renders blank data

### Solution

Update RawDataTable to accept parsed CSVs rather than raw CSVs, and render the data with an optional offset that is applied for UI pagination. Feature flagged this here:

https://github.com/influxdata/idpe/pull/9011

UI-pagination

### CODE REVIEW

File: src/timeMachine/components/RawFluxDataTable.tsx [hunk 1]
```diff
@@ -27,25 +32,67 @@ interface State {
...
+      startRow,
+    } = this.props
+    let {data, maxColumnCount} = this.props
 
     const {scrollTop, scrollLeft} = this.state
+
+    const tableWidth = width
+    const tableHeight = height
+
+    if (isFlagEnabled('flowsUiPagination')) {
```
Comment (drdelambre) [inline src/timeMachine/components/RawFluxDataTable.tsx:55]: i can't put my finger on it, but triggering this off of a flag instead of by props feels wrong. what about those other flags below? why aren't they included in this solution?

File: src/timeMachine/components/Vis.tsx [hunk 2]
```diff
@@ -83,16 +90,41 @@ const TimeMachineVis: SFC<Props> = ({
         >
           {isViewingRawData ? (
             <AutoSizer>
-              {({width, height}) =>
-                width &&
-                height && (
+              {({width, height}) => {
+                if (isFlagEnabled('flowsUiPagination')) {
```
Comment (drdelambre) [inline src/timeMachine/components/Vis.tsx:94]: maybe i'm kind of getting it. the flag has nothing to do with the feature, but instead the "is data csv or fromfluxresult" and i'd argue that the migration strategy in giraffe mandates that we allow for both, instead of overloading the data prop with some modality

so add a new prop called something else? parsedData?

**Review by drdelambre — APPROVED** [review]
this makes more sense to me. lemme go hunt down your idpe one too
