### PR TITLE
fix: better handling for empty states in template mode

### LINKED ISSUE #2555: Notebooks: Fix error message on simple table prior to data selection
When I enter a template that includes a simple table visualization panel and no metrics selected, I get this error message: 

This message is confusing. Instead it should display "This cell will display results from the previous cell" until data has been inputed.

### PR DESCRIPTION
**Pull request by joelfried**
Closes #2555 

Screenshots of how notebooks look when loaded from templates without changes to the panels:

Screen Shot 2021-09-13 at 11 48 21 AM
Screen Shot 2021-09-13 at 11 23 04 AM
Screen Shot 2021-09-13 at 11 22 42 AM

### CODE REVIEW

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 58 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=2585)

**Comment by genehynson** [comment]
@drdelambre thoughts on this one? Just want to make sure this change doesn't have any other side effects that you might know of

**Review by drdelambre — CHANGES_REQUESTED** [review]
this is all in the wrong place. have the visualization panel return nothing for it's visual function if there's no query and this should all just work

**Comment by drdelambre** [comment]
make sure query exists here: https://github.com/influxdata/ui/blob/master/src/flows/pipes/Visualization/index.ts#L18
and make sure the `_build` function is returning something

File: src/flows/pipes/RawFluxEditor/index.ts [hunk 1]
```diff
@@ -33,11 +32,9 @@ export default register => {
...
           data.queries[data.activeQuery].text.replace(PREVIOUS_REGEXP, query)
         )
-        find(ast, node => !!Object.keys(node.comments || {}).length).forEach(
-          node => {
-            delete node.comments
-          }
-        )
+        if (!ast.body.length) {
+          return ''
+        }
```
Comment (genehynson) [inline src/flows/pipes/RawFluxEditor/index.ts:37]: a change must have been made in the wasm because now `parse` handles comments differently. `parse` removes them automatically and the property `.comments` no longer exists.

**Comment by genehynson** [comment]
Thanks for the feedback @drdelambre ! I refactored the implementation - let me know what you think

File: src/flows/pipes/RawFluxEditor/index.ts (hunk 1 above)
Comment (drdelambre) [reply src/flows/pipes/RawFluxEditor/index.ts:37]: I don't think the distinction matters for this pr, but in case we have to do something with comments or query comparison later, are you saying that a valid query, with a comment and some flux, when passed through parse, then through format, will have the comments removed?

**Review by drdelambre — APPROVED** [review]
This will work and fixes the problem, but I don't think the reasoning is correct

File: src/flows/pipes/RawFluxEditor/index.ts (hunk 1 above)
Comment (genehynson) [reply src/flows/pipes/RawFluxEditor/index.ts]: after more testing, it looks like I was wrong. We still do need to parse comments. Reverted this change
