### PR TITLE
fix: clicking on the markdown doesnt make it editable

### LINKED ISSUE #2674: Cant click on a link in a markdown panel
whenever i try to click on a link in a markdown panel, it switches into edit mode. even when the notebook is in presentation mode. super weird, it shouldn't do that.

also while were in there, the markdown panel shouldn't show up as editable if the notebook is in presentation mode at all, even if the panel was in edit mode when the notebook was switched into presentation mode

### PR DESCRIPTION
**Pull request by asalem1**
Closes #2674 

This PR updates the markdown panel so that clicking on it while the markdown pipe is in `preview` mode doesn't make it editable. It also introduces a new pattern where a flow that's in presentation will display the markdown as being in preview mode

markdown-pipe

### CODE REVIEW

File: src/flows/pipes/Markdown/view.tsx [hunk 1]
```diff
@@ -45,10 +43,10 @@ const MarkdownPanel: FC<PipeProp> = ({Context}) => {
     </Suspense>
   )
 
-  if (data.mode === 'preview') {
+  if (flow.readOnly || data.mode === 'preview') {
```
Comment (genehynson) [inline src/flows/pipes/Markdown/view.tsx:46]: good call!

**Review by genehynson — APPROVED** [review]

File: src/flows/pipes/Markdown/view.tsx [hunk 2]
```diff
@@ -12,17 +12,15 @@ import MarkdownModeToggle from './MarkdownModeToggle'
...
+import {FlowContext} from 'src/flows/context/flow.current'
 
 const MarkdownMonacoEditor = lazy(() =>
   import('src/shared/components/MarkdownMonacoEditor')
 )
 
 const MarkdownPanel: FC<PipeProp> = ({Context}) => {
   const {data, update} = useContext(PipeContext)
-
-  const handlePreviewClick = (): void => {
```
Comment (drdelambre) [inline src/flows/pipes/Markdown/view.tsx:23]: I am fully ok with this functionality change

**Review by drdelambre — APPROVED** [review]
