### PR TITLE
fix(3707/4021/4479): notebooks alerts multiple predicates, don't hold pipe threshold state after pipe deletion, and have flux not spam the endpoint.

### LINKED ISSUE #3707: Notebooks(Alert): Alert messages are being received as spam
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. In AWS EC2 set up a micro instance with a simple HTTP listener that echos messages back to the console
2. Open Influxdbv2 (note that during this test the feature flag 'notebooksNewEndpoints') was set
3. Add test data to a bucket with data points that will trigger a critical threshold alert
4. Create a new Alert Notebook
5. Create a query based on the test data
6. In the alerts section define a threshold designed to trigger an alert notification 
7. In the endpoints section select HTTP and set the URL to the EC2 instance.  In this case plain HTTP with no tokens or authentication. 
8. Generate more test data with timestamps in the future and values to trigger the notification
9. Export the Notebook as a task 
10. Monitor the EC2 instance console for messages

**Expected behavior:**

Expected to receive one notification, just as when a similar Check-Endpoint-Rule is created with classic alerts. 

**Actual behavior:**

The listener is receiving scores of alerts.  This spam is repeated at a pulse equal to the value of the "Check Every" field in the Notebook alert definition. It keeps repeating well after the last data point has passed. 

From the message content, it appears a message is generated for every point in the data set.

**Visual Proof:**

**Console before creating/activating task**
ClassicCheckHTTPNotifiyListenerConsole01
Note one message from the traditional Check-Endp-Rule configuration in Alerts. 

**The Alert Definition**
NotebooksAlert01
Associated data set to be added below. 

**Console after notfication triggered(first time)**
NotebookGeneratedCheckNotifications01

**Note Similar Behavior with Slack Notification**
NotebookGeneratedCheckNotificationsSlack01
This was also encountered when exploring notifications with Slack a couple of days ago. 

## About your environment

**Environment info:**

Testing in K8S-IDPE remocal. 

last UI commit
```
commit a918e664f19a21d33b21fe2c19c7cac8aa01c573 (upstream/master, origin/master, origin/HEAD, master)
Author: Palakp41 <palak@influxdata.com>
Date:   Tue Jan 25 17:16:27 2022 -0800
```
last K8S-IDPE commit
```
commit 84c1d4fd7f71ca41759a5f31e3c245c59f3bd4da (HEAD -> master, origin/master, origin/HEAD)
Author: Hercules Mango Churchill <alchemy@influxdata.com>
Date:   Wed Jan 26 02:00:44 2022 +0000
```

**Data Set**
```
jsoucno,jev=haf mag=8.1
jsoucno,jev=haf mag=8.75
jsoucno,jev=haf mag=7.99
jsoucno,jev=haf mag=7.3
jsoucno,jev=haf mag=6.67
jsoucno,jev=haf mag=6.5
jsoucno,jev=haf mag=6.398
jsoucno,jev=haf mag=6.158
jsoucno,jev=haf mag=6.0631
jsoucno,jev=haf mag=6.61
jsoucno,jev=haf mag=6.72
jsoucno,jev=haf mag=7.28
jsoucno,jev=haf mag=8.25
jsoucno,jev=haf mag=8.6
jsoucno,jev=haf mag=9.34
jsoucno,jev=haf mag=8.76
jsoucno,jev=haf mag=7.88
jsoucno,jev=haf mag=8.094
jsoucno,jev=haf mag=32.25
jsoucno,jev=haf mag=6.06
```
Second to last point intended to trigger alert. 

**LIstener Used**
for convenience

```javascript
const fs = require('fs')
const express = require('express')
const app = express()
const port = 3000
const https = require('https')
const privateKey = fs.readFileSync('./ssl/express-selfsigned.key')
const certificate = fs.readFileSync('./ssl/express-selfsigned.crt')

app.get('/', (req, res) => {
  res.send('Hello World!')
})

app.post('/', (req,res) => {
        console.log('POST')

        let body = ''

        console.log(`HEADERS: ${JSON.stringify(req.headers)}`)

        req.on('data', (data) => {

                console.log(`DATA: ${data}`)
                body += data
        })

        req.on('end', () => {
                res.writeHead(200, {'Content-Type': 'text'})
                res.end(`received: \n ${body} \n`)
        })

//      res.send('POST received\n')
})

app.listen(port, '0.0.0.0', () => {
  console.log(`Example app listening at http://0.0.0.0:${port}`)
})

const httpsServer = https.createServer({key: privateKey, cert: certificate}, app)
httpsServer.listen(443, () => {
   console.log(`Example app listening for HTTPS`)
})


```

### LINKED ISSUE #4021: Notebook(Alerts): multiple variables in Alert definition generates uncompilable flux in exported task
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Setup an echo listener to receive HTTP messages 
2. Go to Influxdbv2 UI (note that during this test the feature flag 'notebooksNewEndpoints' was set)
3. Add test data with at least two numeric fields to a bucket
4. Create an Alert Notebook
5. Using the test data define the query to use all numeric fields 
6. In the alert section define a trigger using the first numeric field AND the second numeric field. 
7. In the alert section choose basic HTTP with the endpoint from step 1
8. Click "Export Alert Task"
9. Locate the generated task in Tasks from the nav bar. e.g. Tasks > Notebook Task for local_XXXXX
10. Click Run. The task is scheduled. 
11. Return to the tasks list via the Nav Bar. And check Last Run Status 

**Expected behavior:**

Expected the task to run successfully.

**Actual behavior:**

Last Run Status is failed.  
The logs show the message. 

```
Unexpected error from query; Err: error @26:36-26:56: expected bool but found (r:{A with ixs:B}) => bool (function): error @26:36-26:56: expected bool but found (r:{A with ixs:B}) => bool (function)
```

Edit the task and the flux script shows a compilation error on line 26. 

```
trigger = (r) => r["dur"] > 20 and (r) => r["ixs"] > 28
```

**Visual Proof:**

NBAlert2Vars01

The generated flux script in the task editor
NBAlert2VarsGenFlux01

## About your environment

**Environment info:**

Testing against K8SIDPE Remocal 

Latest commit in project UI

```
commit 22850c6b4a45fa63c8e8cf267439f90cc8e58460 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Author: Jakub Bednář <jakub.bednar@gmail.com>
Date:   Mon Mar 7 08:19:59 2022 +0100
```

Latest commit in K8SIDPE

```
commit 7f2c8fcedb1170828a73670afccd8565685fcf74 (HEAD -> master, origin/master, origin/alchemy/automatic, origin/HEAD)
Author: Hercules Mango Churchill <alchemy@influxdata.com>
Date:   Mon Mar 7 08:17:01 2022 +0000
```

### LINKED ISSUE #4479: Notebook(alerts): threshold state is being maintained across deletion/re-creation
Found bug, and including fix in already ongoing PR. But documenting here for what it was.

https://user-images.githubusercontent.com/10232835/165152312-51962d2d-aa44-4c95-9658-d649d0ac87ed.mov

### PR DESCRIPTION
**Pull request by wiedld**
Closes #3707 
Closes #4021 
Closes #4479
Also fixed one other found bug.

## Issues/Bugs:
* bug 4021. The addition of multiple thresholds, resulted in invalid flux being exported to a task.
     * flux was writing `(r) => r["a"] > 0 and (r) => r["a"] = 0` . This is an incorrect lambda.
* Bug found. We were setting the default `threshold.field` to a string value `"_value"`.
     * this was occurring even without a user selecting a field.
     * Screen Shot 2022-03-09 at 7 04 58 PM
     * produced flux with `r["_value]`
* bug 3707: alerts are being received as spam
     * the filter/threshold-predicate was being given to the monitor.check() method, but never applied as a transformation in the current query
     * additionally, we have multiple rows piped to monitor.notify() --> instead of limiting to 1. For each row, a notification gets sent.
* bug 4479:
    * make threshold panel. Delete panel --> state was being persisted.
    * FIX: Delete panel --> thresholds are deleted --> re-make panel, now get blank thresholds (clean state).

## Visual proof:

https://user-images.githubusercontent.com/10232835/165164243-d6c5d10c-8771-4d87-9301-13564c27ea14.mp4

* re-check (on this new branch/PR) that we still have functional:
   * deadman checks
   * error thresholds in graph 

## Resultant Query:
Parts of the query updated/changed. (Not the full task query. See vid for that.)

```
trigger = (r) => r["co"] > 0.2 and r["humidity"] < 20 and (r["temperature"] > 0 and r["temperature"] < 100)

task_data
    |> schema["fieldsAsCols"]()
    |> set(
        key: "_notebook_link",
        value:
            "https://twodotoh-dev-denisewiedl20220405130506.remocal.influxdev.co/orgs/9c5955fc99a60b8f/notebooks/6014cd2c58952000",
    )
    |> filter(fn: (r) => r["_measurement"] == "airSensors")
    |> monitor["check"](data: check, messageFn: messageFn, crit: trigger)
    |> filter(fn: trigger)
    |> keep(columns: ["_value", "_time", "_measurement"])
    |> limit(n: 1, offset: 0)
    |> monitor["notify"](
        data: notification,
        endpoint:
            http.endpoint(url: "https://www.example.com/endpoint")(
                mapFn: (r) => {
                    body = {r with _version: 1}

                    return {headers: {"Content-Type": "application/json"}, data: json.encode(v: body)}
                },
            ),
    )
``` 

## Future work (not done in this PR):
* form validation for Notebook Alerts (issue 4229)
* use of schema (issue 4080) for:
   * form validation
   * only can select fields, which belong to the measurement chosen in the Alerts panel

### CODE REVIEW

File: src/flows/pipes/Notification/endpoints/HTTP/index.ts [hunk 1]
```diff
@@ -55,11 +55,15 @@ export default register => {
         task_data
           |> schema["fieldsAsCols"]()
               |> set(key: "_notebook_link", value: "${window.location.href}")
+          |> filter(fn: ${measurement})
```
Comment (wiedld) [inline src/flows/pipes/Notification/endpoints/HTTP/index.ts:58]: monitor.check() will fail if we have >1 measurement in the piped data.

Even once the query builder forces a single measurement, it will still be possible (in the raw flux editor) to have >1 measurement. Therefore, this requirement in the Alerts Panel will not go away.

File: src/flows/pipes/Notification/endpoints/AWS/index.ts [hunk 2]
```diff
@@ -26,14 +26,18 @@ export default register => {
...
       |> set(key: "_notebook_link", value: "${window.location.href}")
+  |> filter(fn: ${measurement})
 	|> monitor["check"](
 		data: check,
 		messageFn: messageFn,
 		crit: trigger,
 	)
+  |> filter(fn: trigger)
+  |> keep(columns: ["_value", "_time", "_measurement"])
+  |> limit(n: 1, offset: 0)
```
Comment (wiedld) [inline src/flows/pipes/Notification/endpoints/AWS/index.ts:40]: FIX: reduce cardinality by selecting columns (keep()) --> then apply limit()

File: src/flows/pipes/Visualization/threshold.ts [hunk 3]
```diff
@@ -18,61 +18,54 @@ export interface ErrorThreshold extends Threshold {
...
+  },
+  'not-equal': {
+    name: 'not equal to',
+    format: ThresholdFormat.Value,
+    condition: data => `${lambdaPrefix} (r["${data.field}"] != ${data.value})`,
+  },
+}
+
 export const COMMON_THRESHOLD_TYPES = {
+  ...EQUALITY_THRESHOLD_TYPES,
```
Comment (wiedld) [inline src/flows/pipes/Visualization/threshold.ts:37]: We should have a single point of definition for `equal` and `not-equal`.
Rather than having 2 points of definition.

File: src/flows/pipes/Notification/Measurement.tsx [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+// Utils
+import {event} from 'src/cloud/utils/reporting'
+
+interface Props {
+  readOnly?: boolean
+}
+
+const Measurement: FC<Props> = ({readOnly}) => {
+  const {data, update, results} = useContext(PipeContext)
+  const [measurement, setMeasurement] = useState(data.measurement || null)
```
Comment (drdelambre) [inline src/flows/pipes/Notification/Measurement.tsx:24]: please dont mirror state within the view layer like this as it causes weird bugs. just reference `data.measurement` and update the state with the `update` function

File: src/flows/pipes/Notification/endpoints/PagerDuty/index.ts [hunk 5]
```diff
@@ -21,14 +21,18 @@ export default register => {
...
-  |> set(key: "_notebook_link", value: "${window.location.href}")  
+  |> set(key: "_notebook_link", value: "${window.location.href}")
+  |> filter(fn: ${measurement})
   |> monitor["check"](
 		data: check,
 		messageFn: messageFn,
     crit: trigger,
 	)
+  |> filter(fn: trigger)
+  |> keep(columns: ["_value", "_time", "_measurement"])
```
Comment (drdelambre) [inline src/flows/pipes/Notification/endpoints/PagerDuty/index.ts:34]: i dont understand these additions. what were you trying to address?

File: src/flows/pipes/Notification/index.ts [hunk 6]
```diff
@@ -1,5 +1,10 @@
 import View from './view'
 import ReadOnly from './readOnly'
+import {PipeData} from 'src/types'
+
+const removeNotificationThresholds = data => {
+  delete data.thresholds
```
Comment (drdelambre) [inline src/flows/pipes/Notification/index.ts:6]: this is not what that function is for. what are you trying to do here? the next step in the chain is that `data` gets deleted,  so  i'm unsure the purpose of removing a field from it before removing the whole object

File: src/flows/pipes/Visualization/threshold.ts [hunk 7]
```diff
@@ -18,31 +18,28 @@ export interface ErrorThreshold extends Threshold {
...
 }
 
+export const lambdaPrefix = '(r) =>'
+
 export const COMMON_THRESHOLD_TYPES = {
   greater: {
     name: 'greater than',
     format: ThresholdFormat.Value,
-    condition: data => `(r) => (r["${data.field}"] > ${data.value})`,
+    condition: data => `${lambdaPrefix} (r["${data.field}"] > ${data.value})`,
```
Comment (drdelambre) [inline src/flows/pipes/Visualization/threshold.ts:41]: i'm not following. this work feels unrelated, why was this change  made in this PR?

**Comment by drdelambre** [comment]
why is it that we can only have one measurement?

File: src/flows/pipes/Notification/endpoints/PagerDuty/index.ts (hunk 5 above)
Comment (wiedld) [reply src/flows/pipes/Notification/endpoints/PagerDuty/index.ts:34]: Notification endpoints were being spammed. This is because the alerts were being triggered:
1. without the filter being applied at all
   * this is because alert.check() creates a separate task.
   * the `trigger` was only being applied within the alert check task.
   * it was NOT being applied in the current flux query. Therefore, monitor.notify() was always occurring (because `|> filter(fn: trigger)` was not occurring)

2. even once the filter is applied, there is several rows of data. Each row of data --> triggers a separate notification in the `monitor.notify()` 
   * use `keep()` to reduce cardinality of the data.
   * use `limit()` to then have a single row of data

A full description of what we are doing, and with the feedback from the flux team that this^^ query is correct, is available here:  https://influxdata.slack.com/archives/C0AD7FFS9/p1647972735067469

File: src/flows/pipes/Notification/index.ts (hunk 6 above)
Comment (wiedld) [reply src/flows/pipes/Notification/index.ts:6]: This error was occurring:
https://github.com/influxdata/ui/issues/4479

That exact change, fixed the error.
It was occurring for the javascript pointer object (the array), but not the primitive (measurement).

File: src/flows/pipes/Visualization/threshold.ts (hunk 7 above)
Comment (wiedld) [reply src/flows/pipes/Visualization/threshold.ts:41]: See how the `lambdaPrefix` is then used in the:
```
THRESHOLD_TYPES[threshold.type].condition(threshold))
      .map((cond, i) => (i > 0 ? cond.split(lambdaPrefix)[1] : cond))
      .join(' and ')
```

The purpose is to fix this bug: https://github.com/influxdata/ui/issues/4021

**Comment by wiedld** [comment]
> why is it that we can only have one measurement?

Because that is a requirement of monitor.check(). It will fail if you provide >1 measurement.

File: src/flows/pipes/Notification/Measurement.tsx (hunk 4 above)
Comment (wiedld) [reply src/flows/pipes/Notification/Measurement.tsx]: done.

File: src/flows/pipes/Notification/index.ts (hunk 6 above)
Comment (drdelambre) [reply src/flows/pipes/Notification/index.ts:6]: please remove this improperly added memo instead. it's preventing the threshold allocation from being properly recycled with garbage collection
https://github.com/influxdata/ui/blob/master/src/flows/pipes/Notification/Threshold.tsx#L40

File: src/flows/pipes/Visualization/threshold.ts (hunk 7 above)
Comment (drdelambre) [reply src/flows/pipes/Visualization/threshold.ts:41]: k so `lambdaPrefix` is just a const (should be `LAMBDA_PREFIX` in that case, and should be applied more uniformly across the codebase in case we change it). But if the intent is to just apply it on locations that might later have to be passed through this split to match this conditional rendering, then we're creating an ill defined coupling between the definition of the condition and code that conditionally mutates it. while you've updated the current dealings, there's nothing enforcing that relationship down the line, meaning these have a good chance of drifting.

since it doesn't seem like you actually want / need the `(r) =>` to be configurable (correct me if i read this wrong), a better interface might be to modify the condition functions to handle the rendering themselves by updating the function signature to something like `condition: (data: Record<"field"|"value", string>, prefix?: string) => string`, or to remove the prefix from the condition interface altogether and just conditionally apply the prefix to the whole string, so... 
```
const thresholds  = '(r) => ` + (THRESHOLD_TYPES[threshold.type].condition(threshold))
      .map((cond, i) => (i > 0 ? cond.split(lambdaPrefix)[1] : cond))
      .join(' and '))
```

File: src/flows/pipes/Notification/index.ts (hunk 6 above)
Comment (wiedld) [reply src/flows/pipes/Notification/index.ts:6]: It's not the memoize. (That component is completely unmounted.)

Tested:
1. reverted the commit with the `removeNotificationThresholds()`
2. removed the memo.
  * Screen Shot 2022-04-26 at 10 01 34 AM

3. the issue/bug is still present (without the memo).


https://user-images.githubusercontent.com/10232835/165354223-7a3c24a8-bbef-47af-be1d-3b03ea81d0ad.mov

Comment (drdelambre) [reply src/flows/pipes/Notification/index.ts:6]: does that mean that we're not properly deep cloning from the `initial` state?

Comment (wiedld) [reply src/flows/pipes/Notification/index.ts:6]: agreed. it's a pass by reference error somewhere.
I was forcing deletion of the reference, to prevent this error.

We could alternatively enforce a deep cloning of the init state whenever we addPipe. I like that idea. Will do.

**Comment by drdelambre** [comment]
please remove the `.map((cond, i) => (i > 0 ? cond.split(lambdaPrefix)[1] : cond))` mechanism. it is fragile and causes unnecessary implicit coupling of concepts

File: src/flows/pipes/Visualization/threshold.ts (hunk 7 above)
Comment (wiedld) [reply src/flows/pipes/Visualization/threshold.ts]: removed per request.

**Comment by wiedld** [comment]
> please remove the `.map((cond, i) => (i > 0 ? cond.split(lambdaPrefix)[1] : cond))` mechanism. it is fragile and causes unnecessary implicit coupling of concepts

removed per request.
Note that there is still a coupling between these parts of the codebase. But it's no longer surfaced as a coupled concept...will just have to catch drift as reported bugs.

File: src/flows/pipes/Notification/Measurement.tsx [hunk 8]
```diff
@@ -0,0 +1,88 @@
...
+
+interface Props {
+  readOnly?: boolean
+}
+
+const Measurement: FC<Props> = ({readOnly}) => {
+  const {data, update, results} = useContext(PipeContext)
+  const {measurement} = data
+
+  const measurements = Array.from(
```
Comment (drdelambre) [inline src/flows/pipes/Notification/Measurement.tsx:26]: not for this pr, as it extends to the edge case, but it'd be nice if this component didn't render when `measurements.length === 1`, just to reduce the number of choices

File: src/flows/pipes/Notification/Measurement.tsx [hunk 9]
```diff
@@ -0,0 +1,88 @@
...
+    </Dropdown.Button>
+  )
+
+  return (
+    <FlexBox
+      direction={FlexDirection.Row}
+      margin={ComponentSize.Medium}
+      alignItems={AlignItems.FlexStart}
+      testID="component-spacer"
+      style={{padding: '24px 0'}}
```
Comment (drdelambre) [inline src/flows/pipes/Notification/Measurement.tsx:74]: it'd be nice to see these moved out into a class, but not a blocker

**Review by drdelambre — APPROVED** [review]
