### PR TITLE
fix: simple table 0 of undefined and pagination bugs

### LINKED ISSUE #1813: SimpleTable: Cannot read property '0' of undefined
to repro:
1. ensure you have the simpleTable flag enabled
2. Open data explorer, select raw data view, and open script editor
3. paste the following script
```
import "experimental"
import "experimental/geo"
import "experimental/csv"

csv.from(url: "https://raw.githubusercontent.com/influxdata/influxdb2-sample-data/master/usgs-earthquake-data/all_week-annotated.csv")
  |> filter(fn: (r) => r._measurement == "earthquake" and r._field == "depth")
  |> group(columns: ["_field"])
  |> limit(n: 10)
  |> keep(columns: ["_field", "_value"])
  |> group()
```

Run the query, see the results.

change the `limit(n: 10)` to `limit(n:20)` and run the script again. notice the error.

image

### PR DESCRIPTION
**Pull request by genehynson**
Closes #1813 and #1714

The original issues are resolved simply by changing the offset calculation to prevent the offset from becoming -1. However, this bug highlighted another issue with simpletable where the records from the `n-1` page were duplicated on the `nth` page. The solution to that was to set the `totalPages` variable whenever the result set changes or the height of the table changes. We cannot calculate the `totalPages` using `size` and `offset` because those numbers change as each page is rendered and not all pages show the same number of records.

I added unit and cypress tests

### CODE REVIEW

**Review by Asalem1 — APPROVED** [review]

File: src/visualization/context/pagination.tsx [hunk 1]
```diff
@@ -53,7 +53,9 @@ export const PaginationProvider: FC<PaginationProviderProps> = ({
 
   const setPage = useCallback(
     (page: number) => {
-      setOffset(Math.min(Math.max(0, (page - 1) * size), total - size))
+      setOffset(
+        Math.min(Math.max(0, (page - 1) * size), Math.max(0, total - size))
```
Comment (subirjolly) [inline src/visualization/context/pagination.tsx:57]: Quick unit test!
example:
page: 1
size: 2
total: 11

Now see if offset is correct.

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 59 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=master)

File: src/visualization/context/pagination.tsx (hunk 1 above)
Comment (genehynson) [reply src/visualization/context/pagination.tsx]: good catch. This ended up being a pretty involved fix but take a look at what I ended up doing and let me know your thoughts.

Comment (subirjolly) [reply src/visualization/context/pagination.tsx]: will approve as soon as you push up your fix again.

**Review by subirjolly — APPROVED** [review]
