### PR TITLE
fix: don't show bucket schema info on OSS bucket meta cards

### LINKED ISSUE #2520: Show bucket schema info only on cloud
Currently, the implicit/explicit bucket schema info is shown for the bucket list on OSS. Since OSS doesn't have support for implicit/explicit schema, we should prevent this designation from showing up - it will always be "implicit".

### PR DESCRIPTION
**Pull request by wbaker85**
Closes #2520

Prevents bucket schema info from being shown on OSS, which does not have the concept of bucket schema.

### CODE REVIEW

**Review by hoorayimhelping — APPROVED** [review]

**Comment by wbaker85** [comment]
Guess this broke the unit tests so I'll need to figure out how to resolve that.

**Comment by wbaker85** [comment]
> Guess this broke the unit tests so I'll need to figure out how to resolve that.

should be fixed now

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 57 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=2524)

File: src/buckets/components/BucketCardMeta.tsx [hunk 1]
```diff
@@ -55,6 +56,10 @@ const BucketCardMeta: FC<Props> = ({bucket, notify}) => {
     <span data-testid="bucket-schemaType"> {schemaLabel} </span>
   )
 
+  const bucketInfo = CLOUD
+    ? [schemaBlock, persistentBucketMeta]
```
Comment (jrenee42) [inline src/buckets/components/BucketCardMeta.tsx:60]: please reverse the order!  (to keep the current order of the meta data, then the schema block

**Review by jrenee42 — CHANGES_REQUESTED** [review]

**Review by jrenee42 — APPROVED** [review]
