### PR TITLE
fix: various bug fixes in notebooks

### LINKED ISSUE #890: Notebooks: Updating filter doesn't take effect
If you select a bucket and filter, and run preview, it works fine. If you then change the filters, the new filters will show in the UI but the query continues to execute with the original filters. You need to refresh the page for the new filters to take effect.

Rick saw something similar when he selected a different bucket. The query continued to run against the original bucket.

### PR DESCRIPTION
**Pull request by genehynson**
Closes #890

- Fixes issue where results table doesn't show results from latest query due to memoization
- Fixes issue where visualization panel shows "an error has occurred" after executing some queries due to recent annotations changes to time machine
- Fixes issue where multiple list items in metric selector had the same key
- Adds e2e test for metric selector
- Adds testIDs to some components to make testing easier

- [x] [E2E Tests pass in k8s-idpe](https://docs.influxdata.io/development/guides/local-development/#three-ways-to-run-the-ui-e2e-tests-against-the-kind-cluster) (applicable only if you edited Cypress tests)

### CODE REVIEW

**Comment by hercules-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 42 | :red_circle:
accessibility | 96 | :green_circle:
best-practices | 93 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :question:

File: src/flows/components/panel/Results.tsx [hunk 1]
```diff
@@ -171,7 +174,7 @@ const ResultTable: FC<TableProps> = ({
         </Table>
       )
     })
-  }, [height, startRow])
+  }, [height, startRow, results])
```
Comment (drdelambre) [inline src/flows/components/panel/Results.tsx:177]: [ eye twitching intensifies ]

**Review by drdelambre — APPROVED** [review]
🔥
THANKS FOR THE TESTS
