### PR TITLE
fix: add the telegraf troubleshooting docs link

### LINKED ISSUE #1554: Telegraf Refresh: Listen for Data button presents Troubleshooting doc for failures
modal

GIVEN I am on the test your configuration step when creating my telegraf config
WHEN I click on Listen for Data CTA (Listen for Data)
THEN I am presented with a link to the Telegraf troubleshooting document in the event that no data is found.

image 7

image 8

### PR DESCRIPTION
**Pull request by zoesteinkamp**
Closes #1554 

Screen Shot 2021-09-15 at 3 19 56 PM

### CODE REVIEW

**Review by ChitlangeSahas — APPROVED** [review]

File: src/dataLoaders/components/verifyStep/ConnectionInformation.tsx [hunk 1]
```diff
@@ -56,15 +57,25 @@ class ConnectionInformation extends PureComponent<Props> {
     }
   }
 
-  private get additionalText(): string {
+  private get additionalText(): any {
```
Comment (TCL735) [inline src/dataLoaders/components/verifyStep/ConnectionInformation.tsx:60]: This is fine, although the use of `any` seems lazy here but it's not a blocker.

**Review by TCL735 — APPROVED** [review]

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 57 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=2626)

File: src/dataLoaders/components/verifyStep/ConnectionInformation.tsx (hunk 1 above)
Comment (zoesteinkamp) [reply src/dataLoaders/components/verifyStep/ConnectionInformation.tsx:60]: I think the problem is if we define it, the one i added is not a string, and the others are strings. Idk if we could do string || object? i think any just makes it easier for now
