### PR TITLE
fix: add check to not allow only whitespace as bucket name

### LINKED ISSUE #2326: Buckets: can have entire name as white space
Buckets can be created in the ui with white space as the entire name. This is problematic because the name of buckets is clickable, but with white space it is not apparent where the name really is.

- Navigate to Data > Buckets
- Click `+ Create Bucket`
- add a space or multiple spaces to the name
- save
- notice that the list of buckets has an extra bucket with an invisible (white space) name

### PR DESCRIPTION
**Pull request by ChitlangeSahas**
Closes #2326

Adds a check to invalidate bucket names that are only white spaces.

https://user-images.githubusercontent.com/18511823/132388304-6efb040c-ff26-463f-824b-5568217f29ad.mov

### CODE REVIEW

**Review by TCL735 — APPROVED** [review]

File: src/buckets/components/createBucketForm/BucketOverlayForm.tsx [hunk 1]
```diff
@@ -181,6 +181,10 @@ export default class BucketOverlayForm extends PureComponent<Props> {
       return 'This bucket needs a name'
     }
 
+    if (name.trim().length === 0) {
+      return 'Bucket name cannot be only whitespaces'
```
Comment (hoorayimhelping) [inline src/buckets/components/createBucketForm/BucketOverlayForm.tsx:185]: @daviddkkim what do you think of this message? I think we might tweak it for the average user to something like:

>The bucket name can't be empty
or
>Please enter a name with at least $minimum_characters_allowed letters

**Review by hoorayimhelping — APPROVED** [review]
Nice job fixing this, but let's get an opinion on wording of this

File: src/buckets/components/createBucketForm/BucketOverlayForm.tsx (hunk 1 above)
Comment (ChitlangeSahas) [reply src/buckets/components/createBucketForm/BucketOverlayForm.tsx:185]: That is a good point! I didn't think of that..

Comment (daviddkkim) [reply src/buckets/components/createBucketForm/BucketOverlayForm.tsx:185]: I like `Please enter a name with at least $minimum_characters_allowed letters` (or numbers? assuming bucket names can just be numbers)  because its action oriented.

Comment (ChitlangeSahas) [reply src/buckets/components/createBucketForm/BucketOverlayForm.tsx:185]: I can do that!

Comment (ChitlangeSahas) [reply src/buckets/components/createBucketForm/BucketOverlayForm.tsx:185]: What is the minimum number of characters we want the bucket name to be?

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 57 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=2549)

File: src/buckets/components/createBucketForm/BucketOverlayForm.tsx (hunk 1 above)
Comment (daviddkkim) [reply src/buckets/components/createBucketForm/BucketOverlayForm.tsx]: I'm not sure- I think whatever the API allows should be good here

**Review by hoorayimhelping — APPROVED** [review]
