### PR TITLE
fix: use standard dashboard card height when alert is first in a row

### LINKED ISSUE #4596: Bug: Dashboard - "Need more dashboards" covered by "GET MORE DASHBOARDS"
"Need more dashboards" covered by "GET MORE DASHBOARDS"

Image

### PR DESCRIPTION
**Pull request by TCL735**
Closes #4596 

Sets the resource card with the asset limit alert with the correct height when the card is the first one in the row

Screen Shot 2022-05-20 at 12 58 12 PM

### CODE REVIEW

File: src/checkout/CheckoutForm.tsx [hunk 1]
```diff
@@ -118,21 +117,6 @@ const CheckoutForm: FC = () => {
...
-                    <div
-                      className="checkout-form--banner"
-                      key="checkout-form-banner"
-                    >
-                      <strong className="checkout-banner--credit">$250</strong>
-                      <p>credit applied</p>
-                    </div>,
-                  ]}
-                />
-              )}
```
Comment (TCL735) [inline src/checkout/CheckoutForm.tsx:135]: This was creating the "sash" which is from an old experiment. Per the specs and requirements, use a banner instead.

Not this:
Screen Shot 2022-05-20 at 9 47 49 AM


But this:
Screen Shot 2022-05-20 at 10 17 47 AM

File: src/checkout/CheckoutForm.tsx [hunk 2]
```diff
@@ -79,7 +78,7 @@ const CheckoutForm: FC = () => {
           >
             Upgrade to Usage-Based Account
           </h1>
-          {isFlagEnabled('credit250Experiment') && !isPaygCreditActive && (
+          {isFlagEnabled('credit250Experiment') && (
```
Comment (TCL735) [inline src/checkout/CheckoutForm.tsx:81]: Redundant because the `<GoogleOptimizeExperiment>` component will check if payg credit is active or not.

File: src/dashboards/components/dashboard_index/DashboardCards.tsx [hunk 3]
```diff
@@ -69,6 +72,7 @@ class DashboardCards extends PureComponent<Props> {
     pages: 1,
     windowSize: 0,
     pinnedItems: [],
+    dashboardCardHeight: 'inherit',
```
Comment (hoorayimhelping) [inline src/dashboards/components/dashboard_index/DashboardCards.tsx:75]: smart :+1:

File: src/dashboards/components/dashboard_index/DashboardCardsPaginated.tsx [hunk 4]
```diff
@@ -72,30 +88,33 @@ class DashboardCards extends PureComponent<Props> {
     const {pinnedItems} = this.state
 
     return (
-      <div>
```
Comment (hoorayimhelping) [inline src/dashboards/components/dashboard_index/DashboardCardsPaginated.tsx:75]: can you make sure this still works with multiple pages of dashboard cards? I seem to remember this being added in to make scrolling work properly

**Review by hoorayimhelping — APPROVED** [review]
lgtm generally - just make sure the paginated dashboards still work properly with the removal of that one `div`

**Comment by TCL735** [comment]
> lgtm generally - just make sure the paginated dashboards still work properly with the removal of that one `div`

Yes. Paginated dashboards still work with the removal of the extra `<div>`. Here is a video


https://user-images.githubusercontent.com/10736577/169608103-fcccee43-647c-4a81-a861-99d596c0956e.mp4

File: src/dashboards/components/dashboard_index/DashboardCardsPaginated.tsx (hunk 4 above)
Comment (TCL735) [reply src/dashboards/components/dashboard_index/DashboardCardsPaginated.tsx:75]: Still works as far as i can tell. See video.

**Comment by TCL735** [comment]
Here is a second video with scrollbars and pagination.


https://user-images.githubusercontent.com/10736577/169608943-63785227-f07a-4319-abf4-ee49559b94dc.mp4

File: src/dashboards/components/dashboard_index/DashboardCardsPaginated.tsx (hunk 4 above)
Comment (TCL735) [reply src/dashboards/components/dashboard_index/DashboardCardsPaginated.tsx:75]: I added another video that has scrollbars and pagination together.
