### PR TITLE
chore: fixing the next button in arduino wizard

### LINKED ISSUE #5449: firstMile: Arduino - Add capability to hit next on second to last page
On the Execute aggregate page there is no capability to hit the next button.

Image

### PR DESCRIPTION
**Pull request by alexjw3**
Closes #5449

Allowing the next button to be used in the aggregate query page.

### Checklist

Authors and Reviewer(s), please verify the following:

- [x] A PR description, regardless of the triviality of this change, that communicates the value of this PR
- [x] [Well-formatted conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/) that provide context into the change
- [x] Documentation updated or issue created (provide link to issue/PR)
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] Feature flagged, if applicable

### CODE REVIEW

File: src/homepageExperience/containers/ArduinoWizard.tsx [hunk 1]
```diff
@@ -64,46 +64,38 @@ export class ArduinoWizard extends PureComponent<{}, State> {
...
         ),
-      },
-      () => {
-        event(
-          'firstMile.arduinoWizard.next.clicked',
-          {},
-          {
-            clickedButtonAtStep: normalizeEventName(
-              HOMEPAGE_NAVIGATION_STEPS_ARDUINO[this.state.currentStep - 1].name
-            ),
```
Comment (ChitlangeSahas) [inline src/homepageExperience/containers/ArduinoWizard.tsx:81]: Why do we take it out of the setState callback?

File: src/homepageExperience/containers/ArduinoWizard.tsx [hunk 2]
```diff
@@ -225,7 +217,7 @@ export class ArduinoWizard extends PureComponent<{}, State> {
                   size={ComponentSize.Large}
                   color={ComponentColor.Primary}
                   status={
-                    this.state.currentStep < 7
+                    this.state.currentStep < 8
```
Comment (ChitlangeSahas) [inline src/homepageExperience/containers/ArduinoWizard.tsx:220]: to future proof this, we can do `HOMEPAGE_NAVIGATION_STEPS_ARDUINO.length` (?)

File: src/homepageExperience/containers/ArduinoWizard.tsx (hunk 1 above)
Comment (alexjw3) [reply src/homepageExperience/containers/ArduinoWizard.tsx:81]: We take it out because the event is expecting the previous state rather than the updated state.

Comment (ChitlangeSahas) [reply src/homepageExperience/containers/ArduinoWizard.tsx:81]: Then i think we should put that before the setState, to make that explicitly clear.

Comment (hoorayimhelping) [reply src/homepageExperience/containers/ArduinoWizard.tsx:81]: I agree, it's probably better to put it before the call to `setState` so we don't have to do wonky index math when firing the event

Comment (alexjw3) [reply src/homepageExperience/containers/ArduinoWizard.tsx]: I decided instead to not use indexing at all to avoid messiness. See the new commit where we only report the current step rather than the index. This is what we used for previous wizards so could be better for consistency.

Comment (ChitlangeSahas) [reply src/homepageExperience/containers/ArduinoWizard.tsx]: Hmm.. i am a little concerned about replacing the normalizeEventName function. It seems like a good addition for consistency.

Plus, we're going from step names to step numbers, which makes it more confusing to people who are going to read the events. like, 

```
clickedButtonAtStep: Finish
clickedButtonAtStep: 9
```

the first event name is better to follow.

Comment (ChitlangeSahas) [reply src/homepageExperience/containers/ArduinoWizard.tsx]: Or am I misunderstanding the change?

File: src/homepageExperience/containers/ArduinoWizard.tsx [hunk 3]
```diff
@@ -64,46 +64,38 @@ export class ArduinoWizard extends PureComponent<{}, State> {
...
-            clickedButtonAtStep: normalizeEventName(
-              HOMEPAGE_NAVIGATION_STEPS_ARDUINO[this.state.currentStep - 1].name
-            ),
-            currentStep: normalizeEventName(
-              HOMEPAGE_NAVIGATION_STEPS_ARDUINO[this.state.currentStep].name
-            ),
-          }
-        )
+    this.setState({currentStep: Math.max(this.state.currentStep - 1, 1)})
+    event(
```
Comment (ChitlangeSahas) [inline src/homepageExperience/containers/ArduinoWizard.tsx:89]: Now that the event function call is out of the callback, its not guranteed what the state of `currentStep` will be. This might get called before/after the state is updated. 

we should move the event call before the setState for that reason. 

Does that make sense? 

https://stackoverflow.com/a/42038724

File: src/homepageExperience/containers/ArduinoWizard.tsx [hunk 4]
```diff
@@ -64,48 +64,40 @@ export class ArduinoWizard extends PureComponent<{}, State> {
...
-            currentStep: normalizeEventName(
-              HOMEPAGE_NAVIGATION_STEPS_ARDUINO[this.state.currentStep].name
-            ),
-          }
-        )
+    event(
+      'firstMile.arduinoWizard.previous.clicked',
+      {},
+      {
+        clickedButtonAtStep: normalizeEventName(
```
Comment (ChitlangeSahas) [inline src/homepageExperience/containers/ArduinoWizard.tsx:92]: I think this should be `this.state.currentStep` , `clickedButtonAtStep ===> currentStep`

File: src/homepageExperience/containers/ArduinoWizard.tsx [hunk 5]
```diff
@@ -64,48 +64,40 @@ export class ArduinoWizard extends PureComponent<{}, State> {
...
+          HOMEPAGE_NAVIGATION_STEPS_ARDUINO[this.state.currentStep - 1].name
+        ),
+        currentStep: normalizeEventName(
+          HOMEPAGE_NAVIGATION_STEPS_ARDUINO[this.state.currentStep - 2].name
```
Comment (ChitlangeSahas) [inline src/homepageExperience/containers/ArduinoWizard.tsx:96]: I think this should be `this.state.currentStep` instead of `this.state.currentStep - 2`.

File: src/homepageExperience/containers/ArduinoWizard.tsx [hunk 6]
```diff
@@ -64,48 +64,40 @@ export class ArduinoWizard extends PureComponent<{}, State> {
...
-              HOMEPAGE_NAVIGATION_STEPS_ARDUINO[this.state.currentStep].name
-            ),
-          }
-        )
+    event(
+      'firstMile.arduinoWizard.previous.clicked',
+      {},
+      {
+        clickedButtonAtStep: normalizeEventName(
+          HOMEPAGE_NAVIGATION_STEPS_ARDUINO[this.state.currentStep - 1].name
```
Comment (ChitlangeSahas) [inline src/homepageExperience/containers/ArduinoWizard.tsx:93]: And this one looks good.

File: src/homepageExperience/containers/CliWizard.tsx [hunk 7]
```diff
@@ -63,13 +63,6 @@ export class CliWizard extends PureComponent<{}, State> {
...
-    this.setState({
-      currentStep: Math.min(
-        this.state.currentStep + 1,
-        HOMEPAGE_NAVIGATION_STEPS_SHORT.length
-      ),
-    })
-
     event(
       'firstMile.cliWizard.next.clicked',
       {},
```
Comment (ChitlangeSahas) [inline src/homepageExperience/containers/CliWizard.tsx:68]: seems like we're missing the metadata here? (the data about what step the user is on, and where was the next clicked?

**Review by ChitlangeSahas — CHANGES_REQUESTED** [review]
Let's pair up on this tomorrow if needed. I am having some trouble understanding the intent behind changing the eventing logic. And seems like the eventing logic in CLI onboarding needs some work too. 

it might help for you to print the events to console when you click next/previous so you can understand what the values are at certain steps.

File: src/homepageExperience/containers/CliWizard.tsx (hunk 7 above)
Comment (ChitlangeSahas) [reply src/homepageExperience/containers/CliWizard.tsx:68]: This was github minimizing the next code lines, sorry for the false alarm.

**Review by ChitlangeSahas — APPROVED** [review]
